2024-10-09 15:18:10,144 - INFO - App started successfully!
2024-10-09 15:18:10,145 - INFO - Database connected successfully!
2024-10-09 15:18:10,146 - INFO - Started server process [36936]
2024-10-09 15:18:10,146 - INFO - Waiting for application startup.
2024-10-09 15:18:10,147 - INFO - Application startup complete.
2024-10-09 15:24:31,069 - INFO - App started successfully!
2024-10-09 15:24:31,071 - INFO - Database connected successfully!
2024-10-09 15:24:31,071 - INFO - Started server process [37892]
2024-10-09 15:24:31,072 - INFO - Waiting for application startup.
2024-10-09 15:24:31,072 - INFO - Application startup complete.
2024-10-09 15:24:34,704 - INFO - Shutting down
2024-10-09 15:24:34,807 - INFO - Waiting for application shutdown.
2024-10-09 15:24:34,808 - INFO - Application shutdown complete.
2024-10-09 15:24:34,808 - INFO - Finished server process [37892]
2024-10-09 15:24:40,714 - INFO - App started successfully!
2024-10-09 15:24:40,715 - INFO - Database connected successfully!
2024-10-09 15:24:40,716 - INFO - Started server process [37951]
2024-10-09 15:24:40,716 - INFO - Waiting for application startup.
2024-10-09 15:24:40,717 - INFO - Application startup complete.
2024-10-09 15:24:44,433 - INFO - Shutting down
2024-10-09 15:24:44,534 - INFO - Waiting for application shutdown.
2024-10-09 15:24:44,534 - INFO - Application shutdown complete.
2024-10-09 15:24:44,535 - INFO - Finished server process [37951]
2024-10-09 15:24:46,623 - INFO - App started successfully!
2024-10-09 15:24:46,625 - INFO - Database connected successfully!
2024-10-09 15:24:46,625 - INFO - Started server process [37984]
2024-10-09 15:24:46,625 - INFO - Waiting for application startup.
2024-10-09 15:24:46,626 - INFO - Application startup complete.
2024-10-09 15:25:29,506 - INFO - Shutting down
2024-10-09 15:25:29,607 - INFO - Waiting for application shutdown.
2024-10-09 15:25:29,608 - INFO - Application shutdown complete.
2024-10-09 15:25:29,608 - INFO - Finished server process [37984]
2024-10-09 15:25:34,750 - INFO - App started successfully!
2024-10-09 15:25:34,752 - INFO - Database connected successfully!
2024-10-09 15:25:34,752 - INFO - Started server process [38086]
2024-10-09 15:25:34,753 - INFO - Waiting for application startup.
2024-10-09 15:25:34,753 - INFO - Application startup complete.
2024-10-09 15:30:33,336 - INFO - Shutting down
2024-10-09 15:30:33,438 - INFO - Waiting for application shutdown.
2024-10-09 15:30:33,439 - INFO - Application shutdown complete.
2024-10-09 15:30:33,439 - INFO - Finished server process [38086]
2024-10-09 15:30:42,391 - INFO - App started successfully!
2024-10-09 15:30:42,393 - INFO - Database connected successfully!
2024-10-09 15:30:42,393 - INFO - Started server process [38827]
2024-10-09 15:30:42,394 - INFO - Waiting for application startup.
2024-10-09 15:30:42,395 - INFO - Application startup complete.
2024-10-09 15:30:47,114 - INFO - Shutting down
2024-10-09 15:30:47,215 - INFO - Waiting for application shutdown.
2024-10-09 15:30:47,216 - INFO - Application shutdown complete.
2024-10-09 15:30:47,217 - INFO - Finished server process [38827]
2024-10-09 15:30:49,543 - INFO - App started successfully!
2024-10-09 15:30:49,545 - INFO - Database connected successfully!
2024-10-09 15:30:49,546 - INFO - Started server process [38863]
2024-10-09 15:30:49,546 - INFO - Waiting for application startup.
2024-10-09 15:30:49,547 - INFO - Application startup complete.
2024-10-09 15:31:16,378 - INFO - Shutting down
2024-10-09 15:31:16,480 - INFO - Waiting for application shutdown.
2024-10-09 15:31:16,481 - INFO - Application shutdown complete.
2024-10-09 15:31:16,481 - INFO - Finished server process [38863]
2024-10-09 15:31:19,262 - INFO - App started successfully!
2024-10-09 15:31:19,264 - INFO - Database connected successfully!
2024-10-09 15:31:19,264 - INFO - Started server process [38966]
2024-10-09 15:31:19,265 - INFO - Waiting for application startup.
2024-10-09 15:31:19,265 - INFO - Application startup complete.
2024-10-09 15:31:20,877 - INFO - Shutting down
2024-10-09 15:31:20,977 - INFO - Waiting for application shutdown.
2024-10-09 15:31:20,978 - INFO - Application shutdown complete.
2024-10-09 15:31:20,979 - INFO - Finished server process [38966]
2024-10-09 15:31:23,881 - INFO - App started successfully!
2024-10-09 15:31:23,883 - INFO - Database connected successfully!
2024-10-09 15:31:23,884 - INFO - Started server process [38996]
2024-10-09 15:31:23,885 - INFO - Waiting for application startup.
2024-10-09 15:31:23,888 - INFO - Application startup complete.
2024-10-09 15:31:25,299 - INFO - Shutting down
2024-10-09 15:31:25,399 - INFO - Waiting for application shutdown.
2024-10-09 15:31:25,400 - INFO - Application shutdown complete.
2024-10-09 15:31:25,401 - INFO - Finished server process [38996]
2024-10-09 15:31:27,719 - INFO - App started successfully!
2024-10-09 15:31:27,721 - INFO - Database connected successfully!
2024-10-09 15:31:27,721 - INFO - Started server process [39028]
2024-10-09 15:31:27,721 - INFO - Waiting for application startup.
2024-10-09 15:31:27,722 - INFO - Application startup complete.
2024-10-09 15:31:33,450 - INFO - Shutting down
2024-10-09 15:31:33,551 - INFO - Waiting for application shutdown.
2024-10-09 15:31:33,551 - INFO - Application shutdown complete.
2024-10-09 15:31:33,552 - INFO - Finished server process [39028]
2024-10-09 15:31:36,208 - INFO - App started successfully!
2024-10-09 15:31:36,210 - INFO - Database connected successfully!
2024-10-09 15:31:36,211 - INFO - Started server process [39087]
2024-10-09 15:31:36,211 - INFO - Waiting for application startup.
2024-10-09 15:31:36,212 - INFO - Application startup complete.
2024-10-09 15:31:44,647 - INFO - Shutting down
2024-10-09 15:31:44,747 - INFO - Waiting for application shutdown.
2024-10-09 15:31:44,748 - INFO - Application shutdown complete.
2024-10-09 15:31:44,748 - INFO - Finished server process [39087]
2024-10-09 15:31:47,586 - INFO - App started successfully!
2024-10-09 15:31:47,588 - INFO - Database connected successfully!
2024-10-09 15:31:47,589 - INFO - Started server process [39130]
2024-10-09 15:31:47,589 - INFO - Waiting for application startup.
2024-10-09 15:31:47,590 - INFO - Application startup complete.
2024-10-09 15:31:49,892 - INFO - App started successfully!
2024-10-09 15:31:49,894 - INFO - Database connected successfully!
2024-10-09 15:31:49,895 - INFO - Started server process [39157]
2024-10-09 15:31:49,895 - INFO - Waiting for application startup.
2024-10-09 15:31:49,896 - INFO - Application startup complete.
2024-10-09 15:31:55,319 - INFO - Shutting down
2024-10-09 15:31:55,420 - INFO - Waiting for application shutdown.
2024-10-09 15:31:55,421 - INFO - Application shutdown complete.
2024-10-09 15:31:55,422 - INFO - Finished server process [39157]
2024-10-09 15:31:58,694 - INFO - App started successfully!
2024-10-09 15:31:58,695 - INFO - Database connected successfully!
2024-10-09 15:31:58,696 - INFO - Started server process [39190]
2024-10-09 15:31:58,696 - INFO - Waiting for application startup.
2024-10-09 15:31:58,697 - INFO - Application startup complete.
2024-10-09 15:32:01,042 - INFO - App started successfully!
2024-10-09 15:32:01,044 - INFO - Database connected successfully!
2024-10-09 15:32:01,044 - INFO - Started server process [39219]
2024-10-09 15:32:01,045 - INFO - Waiting for application startup.
2024-10-09 15:32:01,046 - INFO - Application startup complete.
2024-10-09 15:32:10,887 - INFO - Shutting down
2024-10-09 15:32:10,987 - INFO - Waiting for application shutdown.
2024-10-09 15:32:10,988 - INFO - Application shutdown complete.
2024-10-09 15:32:10,989 - INFO - Finished server process [39219]
2024-10-09 15:32:46,071 - INFO - App started successfully!
2024-10-09 15:32:46,073 - INFO - Database connected successfully!
2024-10-09 15:32:46,073 - INFO - Started server process [39352]
2024-10-09 15:32:46,073 - INFO - Waiting for application startup.
2024-10-09 15:32:46,074 - INFO - Application startup complete.
2024-10-09 15:32:48,419 - INFO - App started successfully!
2024-10-09 15:32:48,421 - INFO - Database connected successfully!
2024-10-09 15:32:48,422 - INFO - Started server process [39382]
2024-10-09 15:32:48,422 - INFO - Waiting for application startup.
2024-10-09 15:32:48,423 - INFO - Application startup complete.
2024-10-09 15:33:29,053 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/terminalnator/Client_portal/app/routers/user_routes.py", line 15, in signup_endpoint
    return await signup(user)
TypeError: signup() missing 1 required positional argument: 'user'
2024-10-09 15:34:00,489 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/terminalnator/Client_portal/app/routers/user_routes.py", line 15, in signup_endpoint
    return await signup(user)
TypeError: signup() missing 1 required positional argument: 'user'
2024-10-09 15:39:42,294 - INFO - Shutting down
2024-10-09 15:39:42,395 - INFO - Waiting for application shutdown.
2024-10-09 15:39:42,396 - INFO - Application shutdown complete.
2024-10-09 15:39:42,396 - INFO - Finished server process [39382]
2024-10-09 15:39:59,485 - INFO - App started successfully!
2024-10-09 15:39:59,486 - INFO - Database connected successfully!
2024-10-09 15:39:59,487 - INFO - Started server process [39923]
2024-10-09 15:39:59,487 - INFO - Waiting for application startup.
2024-10-09 15:39:59,488 - INFO - Application startup complete.
2024-10-09 15:40:47,127 - INFO - BEGIN (implicit)
2024-10-09 15:40:47,132 - INFO - SELECT users.id AS users_id, users.first_name AS users_first_name, users.last_name AS users_last_name, users.email AS users_email, users.password AS users_password, users.created_at AS users_created_at, users.updated_at AS users_updated_at, users.is_active AS users_is_active 
FROM users 
WHERE users.email = %(email_1)s 
 LIMIT %(param_1)s
2024-10-09 15:40:47,133 - INFO - [generated in 0.00113s] {'email_1': 'user@example.com', 'param_1': 1}
2024-10-09 15:40:47,154 - INFO - ROLLBACK
2024-10-09 15:40:58,156 - INFO - BEGIN (implicit)
2024-10-09 15:40:58,159 - INFO - SELECT users.id AS users_id, users.first_name AS users_first_name, users.last_name AS users_last_name, users.email AS users_email, users.password AS users_password, users.created_at AS users_created_at, users.updated_at AS users_updated_at, users.is_active AS users_is_active 
FROM users 
WHERE users.email = %(email_1)s 
 LIMIT %(param_1)s
2024-10-09 15:40:58,161 - INFO - [cached since 11.03s ago] {'email_1': 'user22@example.com', 'param_1': 1}
2024-10-09 15:40:58,170 - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-10-09 15:40:58,532 - INFO - INSERT INTO users (id, first_name, last_name, email, password, is_active) VALUES (%(id)s::UUID, %(first_name)s, %(last_name)s, %(email)s, %(password)s, %(is_active)s) RETURNING users.created_at, users.updated_at
2024-10-09 15:40:58,532 - INFO - [generated in 0.00047s] {'id': UUID('9c6f6d94-175e-449d-9509-85fc6fdd3418'), 'first_name': 'string', 'last_name': 'string', 'email': 'user22@example.com', 'password': '$2b$12$Gu49TkEkCLmmDYZS3fM3tOCE8MkoTJZOgE9D6rL.uZi39ArmNelZe', 'is_active': False}
2024-10-09 15:40:58,537 - INFO - COMMIT
2024-10-09 15:40:58,548 - INFO - BEGIN (implicit)
2024-10-09 15:40:58,551 - INFO - SELECT users.id, users.first_name, users.last_name, users.email, users.password, users.created_at, users.updated_at, users.is_active 
FROM users 
WHERE users.id = %(pk_1)s::UUID
2024-10-09 15:40:58,551 - INFO - [generated in 0.00042s] {'pk_1': UUID('9c6f6d94-175e-449d-9509-85fc6fdd3418')}
2024-10-09 15:40:59,015 - INFO - ROLLBACK
2024-10-09 15:40:59,018 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 500, in _create_connection
    transport, _ = await asyncio.wait_for(connect_coro, timeout=self.timeout)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1036, in create_connection
    infos = await self._ensure_resolved(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1418, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
  File "/usr/lib/python3.10/asyncio/base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/connection.py", line 45, in _configure_connection
    await self.session.connect()
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 449, in connect
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 446, in connect
    response = await self._create_connection()
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 506, in _create_connection
    raise SMTPConnectError(
aiosmtplib.errors.SMTPConnectError: Error connecting to smtp.example.com on port 587: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/terminalnator/Client_portal/app/routers/user_routes.py", line 15, in signup_endpoint
    return await signup(db, user)
  File "/home/terminalnator/Client_portal/app/controllers/user_controller.py", line 26, in signup
    await send_verification_email(user.email, verification_token)
  File "/home/terminalnator/Client_portal/app/core/email.py", line 33, in send_verification_email
    await fm.send_message(message)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/fastmail.py", line 109, in send_message
    async with Connection(self.config) as session:
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/connection.py", line 23, in __aenter__
    await self._configure_connection()
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/connection.py", line 53, in _configure_connection
    raise ConnectionErrors(
fastapi_mail.errors.ConnectionErrors: Exception raised Error connecting to smtp.example.com on port 587: [Errno -2] Name or service not known, check your credentials or email service configuration
2024-10-09 15:46:01,556 - INFO - Shutting down
2024-10-09 15:46:01,657 - INFO - Waiting for application shutdown.
2024-10-09 15:46:01,658 - INFO - Application shutdown complete.
2024-10-09 15:46:01,658 - INFO - Finished server process [39923]
2024-10-09 15:46:11,271 - INFO - App started successfully!
2024-10-09 15:46:11,272 - INFO - Database connected successfully!
2024-10-09 15:46:11,273 - INFO - Started server process [40409]
2024-10-09 15:46:11,273 - INFO - Waiting for application startup.
2024-10-09 15:46:11,274 - INFO - Application startup complete.
2024-10-09 15:46:42,906 - INFO - BEGIN (implicit)
2024-10-09 15:46:42,914 - INFO - SELECT users.id AS users_id, users.first_name AS users_first_name, users.last_name AS users_last_name, users.email AS users_email, users.password AS users_password, users.created_at AS users_created_at, users.updated_at AS users_updated_at, users.is_active AS users_is_active 
FROM users 
WHERE users.email = %(email_1)s 
 LIMIT %(param_1)s
2024-10-09 15:46:42,915 - INFO - [generated in 0.00189s] {'email_1': 'user3321@example.com', 'param_1': 1}
2024-10-09 15:46:42,920 - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-10-09 15:46:43,284 - INFO - INSERT INTO users (id, first_name, last_name, email, password, is_active) VALUES (%(id)s::UUID, %(first_name)s, %(last_name)s, %(email)s, %(password)s, %(is_active)s) RETURNING users.created_at, users.updated_at
2024-10-09 15:46:43,285 - INFO - [generated in 0.00059s] {'id': UUID('1440186d-9ef2-4ee0-ba02-8d94472f17dd'), 'first_name': 'string', 'last_name': 'string', 'email': 'user3321@example.com', 'password': '$2b$12$aBGkgO6H9zahOvxrANg2iee/JbqijOeLNjRSUF3bsPSFvR.nyTgYS', 'is_active': False}
2024-10-09 15:46:43,287 - INFO - COMMIT
2024-10-09 15:46:43,292 - INFO - BEGIN (implicit)
2024-10-09 15:46:43,295 - INFO - SELECT users.id, users.first_name, users.last_name, users.email, users.password, users.created_at, users.updated_at, users.is_active 
FROM users 
WHERE users.id = %(pk_1)s::UUID
2024-10-09 15:46:43,296 - INFO - [generated in 0.00086s] {'pk_1': UUID('1440186d-9ef2-4ee0-ba02-8d94472f17dd')}
2024-10-09 15:46:43,317 - INFO - ROLLBACK
2024-10-09 15:46:43,320 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 500, in _create_connection
    transport, _ = await asyncio.wait_for(connect_coro, timeout=self.timeout)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1036, in create_connection
    infos = await self._ensure_resolved(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1418, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
  File "/usr/lib/python3.10/asyncio/base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/connection.py", line 45, in _configure_connection
    await self.session.connect()
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 449, in connect
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 446, in connect
    response = await self._create_connection()
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 506, in _create_connection
    raise SMTPConnectError(
aiosmtplib.errors.SMTPConnectError: Error connecting to smtp.example.com on port 587: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/terminalnator/Client_portal/app/routers/user_routes.py", line 15, in signup_endpoint
    return await signup(db, user)
  File "/home/terminalnator/Client_portal/app/controllers/user_controller.py", line 26, in signup
  File "/home/terminalnator/Client_portal/app/core/email.py", line 33, in send_verification_email
    await fm.send_message(message)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/fastmail.py", line 109, in send_message
    async with Connection(self.config) as session:
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/connection.py", line 23, in __aenter__
    await self._configure_connection()
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/connection.py", line 53, in _configure_connection
    raise ConnectionErrors(
fastapi_mail.errors.ConnectionErrors: Exception raised Error connecting to smtp.example.com on port 587: [Errno -2] Name or service not known, check your credentials or email service configuration
2024-10-09 15:47:52,510 - INFO - Shutting down
2024-10-09 15:47:52,611 - INFO - Waiting for application shutdown.
2024-10-09 15:47:52,612 - INFO - Application shutdown complete.
2024-10-09 15:47:52,613 - INFO - Finished server process [40409]
2024-10-09 15:48:41,145 - INFO - App started successfully!
2024-10-09 15:48:41,146 - INFO - Database connected successfully!
2024-10-09 15:48:41,147 - INFO - Started server process [40801]
2024-10-09 15:48:41,147 - INFO - Waiting for application startup.
2024-10-09 15:48:41,148 - INFO - Application startup complete.
2024-10-09 15:48:43,960 - INFO - Shutting down
2024-10-09 15:48:44,061 - INFO - Waiting for application shutdown.
2024-10-09 15:48:44,063 - INFO - Application shutdown complete.
2024-10-09 15:48:44,063 - INFO - Finished server process [40801]
2024-10-09 15:48:49,153 - INFO - App started successfully!
2024-10-09 15:48:49,154 - INFO - Database connected successfully!
2024-10-09 15:48:49,154 - INFO - Started server process [40845]
2024-10-09 15:48:49,155 - INFO - Waiting for application startup.
2024-10-09 15:48:49,155 - INFO - Application startup complete.
2024-10-09 15:48:57,712 - INFO - BEGIN (implicit)
2024-10-09 15:48:57,716 - INFO - SELECT users.id AS users_id, users.first_name AS users_first_name, users.last_name AS users_last_name, users.email AS users_email, users.password AS users_password, users.created_at AS users_created_at, users.updated_at AS users_updated_at, users.is_active AS users_is_active 
FROM users 
WHERE users.email = %(email_1)s 
 LIMIT %(param_1)s
2024-10-09 15:48:57,717 - INFO - [generated in 0.00066s] {'email_1': 'user3321@example.com', 'param_1': 1}
2024-10-09 15:48:57,723 - INFO - ROLLBACK
2024-10-09 15:49:05,275 - INFO - BEGIN (implicit)
2024-10-09 15:49:05,276 - INFO - SELECT users.id AS users_id, users.first_name AS users_first_name, users.last_name AS users_last_name, users.email AS users_email, users.password AS users_password, users.created_at AS users_created_at, users.updated_at AS users_updated_at, users.is_active AS users_is_active 
FROM users 
WHERE users.email = %(email_1)s 
 LIMIT %(param_1)s
2024-10-09 15:49:05,276 - INFO - [cached since 7.56s ago] {'email_1': 'user332g1@example.com', 'param_1': 1}
2024-10-09 15:49:05,280 - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-10-09 15:49:05,659 - INFO - INSERT INTO users (id, first_name, last_name, email, password, is_active) VALUES (%(id)s::UUID, %(first_name)s, %(last_name)s, %(email)s, %(password)s, %(is_active)s) RETURNING users.created_at, users.updated_at
2024-10-09 15:49:05,659 - INFO - [generated in 0.00052s] {'id': UUID('a8a54b19-ac07-42b2-aada-e9785d04f6b0'), 'first_name': 'string', 'last_name': 'string', 'email': 'user332g1@example.com', 'password': '$2b$12$hBspaJwRbw2DqO58nXtFgOOqW5bGhk3uF9rFvDdEg6AoK.ue1T4qy', 'is_active': False}
2024-10-09 15:49:05,661 - INFO - COMMIT
2024-10-09 15:49:05,670 - INFO - BEGIN (implicit)
2024-10-09 15:49:05,672 - INFO - SELECT users.id, users.first_name, users.last_name, users.email, users.password, users.created_at, users.updated_at, users.is_active 
FROM users 
WHERE users.id = %(pk_1)s::UUID
2024-10-09 15:49:05,673 - INFO - [generated in 0.00048s] {'pk_1': UUID('a8a54b19-ac07-42b2-aada-e9785d04f6b0')}
2024-10-09 15:49:05,675 - INFO - ROLLBACK
2024-10-09 15:49:05,678 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/terminalnator/Client_portal/app/routers/user_routes.py", line 15, in signup_endpoint
    return await signup(db, user)
TypeError: object str can't be used in 'await' expression
2024-10-09 15:51:12,521 - INFO - Shutting down
2024-10-09 15:51:12,622 - INFO - Waiting for application shutdown.
2024-10-09 15:51:12,623 - INFO - Application shutdown complete.
2024-10-09 15:51:12,623 - INFO - Finished server process [40845]
2024-10-09 15:51:14,869 - INFO - App started successfully!
2024-10-09 15:51:14,870 - INFO - Database connected successfully!
2024-10-09 15:51:14,871 - INFO - Started server process [41170]
2024-10-09 15:51:14,871 - INFO - Waiting for application startup.
2024-10-09 15:51:14,872 - INFO - Application startup complete.
2024-10-09 15:51:24,902 - INFO - BEGIN (implicit)
2024-10-09 15:51:24,913 - INFO - SELECT users.id AS users_id, users.first_name AS users_first_name, users.last_name AS users_last_name, users.email AS users_email, users.password AS users_password, users.created_at AS users_created_at, users.updated_at AS users_updated_at, users.is_active AS users_is_active 
FROM users 
WHERE users.email = %(email_1)s 
 LIMIT %(param_1)s
2024-10-09 15:51:24,914 - INFO - [generated in 0.00102s] {'email_1': 'user37732g1@example.com', 'param_1': 1}
2024-10-09 15:51:24,921 - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-10-09 15:51:25,303 - INFO - INSERT INTO users (id, first_name, last_name, email, password, is_active) VALUES (%(id)s::UUID, %(first_name)s, %(last_name)s, %(email)s, %(password)s, %(is_active)s) RETURNING users.created_at, users.updated_at
2024-10-09 15:51:25,303 - INFO - [generated in 0.00073s] {'id': UUID('fabad994-75df-40b8-85df-ce4b7ce8cd42'), 'first_name': 'string', 'last_name': 'string', 'email': 'user37732g1@example.com', 'password': '$2b$12$xjS53ouAeZhdMbuOzVI2WOfCWHzBPzz.Klb/05REshvZknR.t.Yhi', 'is_active': False}
2024-10-09 15:51:25,305 - INFO - COMMIT
2024-10-09 15:51:25,310 - INFO - BEGIN (implicit)
2024-10-09 15:51:25,313 - INFO - SELECT users.id, users.first_name, users.last_name, users.email, users.password, users.created_at, users.updated_at, users.is_active 
FROM users 
WHERE users.id = %(pk_1)s::UUID
2024-10-09 15:51:25,314 - INFO - [generated in 0.00066s] {'pk_1': UUID('fabad994-75df-40b8-85df-ce4b7ce8cd42')}
2024-10-09 15:51:25,318 - INFO - ROLLBACK
2024-10-09 15:51:48,543 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/terminalnator/Client_portal/app/routers/user_routes.py", line 22, in signin_endpoint
    return await signup(user)
TypeError: signup() missing 1 required positional argument: 'user'
2024-10-09 15:52:06,808 - INFO - Shutting down
2024-10-09 15:52:06,909 - INFO - Waiting for application shutdown.
2024-10-09 15:52:06,910 - INFO - Application shutdown complete.
2024-10-09 15:52:06,910 - INFO - Finished server process [41170]
2024-10-09 15:52:09,041 - INFO - App started successfully!
2024-10-09 15:52:09,042 - INFO - Database connected successfully!
2024-10-09 15:52:09,043 - INFO - Started server process [41340]
2024-10-09 15:52:09,043 - INFO - Waiting for application startup.
2024-10-09 15:52:09,044 - INFO - Application startup complete.
2024-10-09 15:52:16,789 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/terminalnator/Client_portal/app/routers/user_routes.py", line 22, in signin_endpoint
    return await signup(user)
TypeError: signup() missing 1 required positional argument: 'user'
2024-10-09 15:53:01,189 - INFO - Shutting down
2024-10-09 15:53:01,290 - INFO - Waiting for application shutdown.
2024-10-09 15:53:01,291 - INFO - Application shutdown complete.
2024-10-09 15:53:01,292 - INFO - Finished server process [41340]
2024-10-09 15:53:03,651 - INFO - App started successfully!
2024-10-09 15:53:03,652 - INFO - Database connected successfully!
2024-10-09 15:53:03,653 - INFO - Started server process [41438]
2024-10-09 15:53:03,654 - INFO - Waiting for application startup.
2024-10-09 15:53:03,654 - INFO - Application startup complete.
2024-10-09 15:53:08,075 - INFO - Shutting down
2024-10-09 15:53:08,176 - INFO - Waiting for application shutdown.
2024-10-09 15:53:08,177 - INFO - Application shutdown complete.
2024-10-09 15:53:08,178 - INFO - Finished server process [41438]
2024-10-09 15:54:08,189 - INFO - App started successfully!
2024-10-09 15:54:08,191 - INFO - Database connected successfully!
2024-10-09 15:54:08,195 - INFO - Started server process [41565]
2024-10-09 15:54:08,195 - INFO - Waiting for application startup.
2024-10-09 15:54:08,196 - INFO - Application startup complete.
2024-10-09 15:54:08,297 - INFO - Shutting down
2024-10-09 15:54:08,398 - INFO - Waiting for application shutdown.
2024-10-09 15:54:08,399 - INFO - Application shutdown complete.
2024-10-09 15:54:08,400 - INFO - Finished server process [41565]
2024-10-09 15:54:13,983 - INFO - App started successfully!
2024-10-09 15:54:13,984 - INFO - Database connected successfully!
2024-10-09 15:54:13,985 - INFO - Started server process [41601]
2024-10-09 15:54:13,985 - INFO - Waiting for application startup.
2024-10-09 15:54:13,985 - INFO - Application startup complete.
2024-10-09 15:54:17,177 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/terminalnator/Client_portal/app/routers/user_routes.py", line 22, in signin_endpoint
    return await signup(user)
TypeError: signup() missing 1 required positional argument: 'user'
2024-10-09 15:55:15,262 - INFO - Shutting down
2024-10-09 15:55:15,363 - INFO - Waiting for application shutdown.
2024-10-09 15:55:15,364 - INFO - Application shutdown complete.
2024-10-09 15:55:15,364 - INFO - Finished server process [41601]
2024-10-09 15:55:17,816 - INFO - App started successfully!
2024-10-09 15:55:17,817 - INFO - Database connected successfully!
2024-10-09 15:55:17,818 - INFO - Started server process [41709]
2024-10-09 15:55:17,818 - INFO - Waiting for application startup.
2024-10-09 15:55:17,819 - INFO - Application startup complete.
2024-10-09 15:55:34,390 - INFO - Shutting down
2024-10-09 15:55:34,491 - INFO - Waiting for application shutdown.
2024-10-09 15:55:34,492 - INFO - Application shutdown complete.
2024-10-09 15:55:34,492 - INFO - Finished server process [41709]
2024-10-09 15:55:36,828 - INFO - App started successfully!
2024-10-09 15:55:36,830 - INFO - Database connected successfully!
2024-10-09 15:55:36,831 - INFO - Started server process [41789]
2024-10-09 15:55:36,831 - INFO - Waiting for application startup.
2024-10-09 15:55:36,832 - INFO - Application startup complete.
2024-10-09 15:55:51,387 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/terminalnator/Client_portal/app/routers/user_routes.py", line 22, in signin_endpoint
    return await signin(user)
TypeError: signin() missing 1 required positional argument: 'user'
2024-10-09 15:59:42,865 - INFO - Shutting down
2024-10-09 15:59:42,966 - INFO - Waiting for application shutdown.
2024-10-09 15:59:42,967 - INFO - Application shutdown complete.
2024-10-09 15:59:42,967 - INFO - Finished server process [41789]
2024-10-09 15:59:45,457 - INFO - App started successfully!
2024-10-09 15:59:45,459 - INFO - Database connected successfully!
2024-10-09 15:59:45,460 - INFO - Started server process [42058]
2024-10-09 15:59:45,460 - INFO - Waiting for application startup.
2024-10-09 15:59:45,461 - INFO - Application startup complete.
2024-10-09 15:59:59,022 - INFO - Shutting down
2024-10-09 15:59:59,123 - INFO - Waiting for application shutdown.
2024-10-09 15:59:59,124 - INFO - Application shutdown complete.
2024-10-09 15:59:59,124 - INFO - Finished server process [42058]
2024-10-09 16:01:17,377 - INFO - App started successfully!
2024-10-09 16:01:17,380 - INFO - Database connected successfully!
2024-10-09 16:01:17,381 - INFO - Started server process [42526]
2024-10-09 16:01:17,381 - INFO - Waiting for application startup.
2024-10-09 16:01:17,382 - INFO - Application startup complete.
2024-10-09 16:01:26,527 - INFO - Shutting down
2024-10-09 16:01:26,628 - INFO - Waiting for application shutdown.
2024-10-09 16:01:26,629 - INFO - Application shutdown complete.
2024-10-09 16:01:26,630 - INFO - Finished server process [42526]
2024-10-09 16:01:38,532 - INFO - App started successfully!
2024-10-09 16:01:38,536 - INFO - Database connected successfully!
2024-10-09 16:01:38,537 - INFO - Started server process [42667]
2024-10-09 16:01:38,537 - INFO - Waiting for application startup.
2024-10-09 16:01:38,538 - INFO - Application startup complete.
2024-10-09 16:02:29,144 - INFO - Shutting down
2024-10-09 16:02:29,245 - INFO - Waiting for application shutdown.
2024-10-09 16:02:29,245 - INFO - Application shutdown complete.
2024-10-09 16:02:29,246 - INFO - Finished server process [42667]
2024-10-09 16:02:31,383 - INFO - App started successfully!
2024-10-09 16:02:31,385 - INFO - Database connected successfully!
2024-10-09 16:02:31,386 - INFO - Started server process [42741]
2024-10-09 16:02:31,386 - INFO - Waiting for application startup.
2024-10-09 16:02:31,387 - INFO - Application startup complete.
2024-10-09 16:02:44,573 - INFO - BEGIN (implicit)
2024-10-09 16:02:44,580 - INFO - SELECT users.id AS users_id, users.first_name AS users_first_name, users.last_name AS users_last_name, users.email AS users_email, users.password AS users_password, users.created_at AS users_created_at, users.updated_at AS users_updated_at, users.is_active AS users_is_active 
FROM users 
WHERE users.email = %(email_1)s 
 LIMIT %(param_1)s
2024-10-09 16:02:44,580 - INFO - [generated in 0.00057s] {'email_1': 'string', 'param_1': 1}
2024-10-09 16:02:44,584 - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-10-09 16:02:44,926 - INFO - ROLLBACK
2024-10-09 16:04:22,237 - INFO - Shutting down
2024-10-09 16:04:22,339 - INFO - Waiting for application shutdown.
2024-10-09 16:04:22,340 - INFO - Application shutdown complete.
2024-10-09 16:04:22,341 - INFO - Finished server process [42741]
2024-10-09 16:04:27,105 - INFO - App started successfully!
2024-10-09 16:04:27,111 - INFO - Database connected successfully!
2024-10-09 16:04:27,111 - INFO - Started server process [43000]
2024-10-09 16:04:27,112 - INFO - Waiting for application startup.
2024-10-09 16:04:27,112 - INFO - Application startup complete.
2024-10-09 16:04:31,117 - INFO - App started successfully!
2024-10-09 16:04:31,120 - INFO - Database connected successfully!
2024-10-09 16:04:31,123 - INFO - Started server process [43038]
2024-10-09 16:04:31,124 - INFO - Waiting for application startup.
2024-10-09 16:04:31,124 - INFO - Application startup complete.
2024-10-09 16:04:31,730 - INFO - Shutting down
2024-10-09 16:04:31,831 - INFO - Waiting for application shutdown.
2024-10-09 16:04:31,832 - INFO - Application shutdown complete.
2024-10-09 16:04:31,832 - INFO - Finished server process [43038]
2024-10-09 16:04:33,925 - INFO - App started successfully!
2024-10-09 16:04:33,926 - INFO - Database connected successfully!
2024-10-09 16:04:33,927 - INFO - Started server process [43073]
2024-10-09 16:04:33,927 - INFO - Waiting for application startup.
2024-10-09 16:04:33,927 - INFO - Application startup complete.
2024-10-09 16:05:16,672 - INFO - BEGIN (implicit)
2024-10-09 16:05:16,676 - INFO - SELECT users.id AS users_id, users.first_name AS users_first_name, users.last_name AS users_last_name, users.email AS users_email, users.password AS users_password, users.created_at AS users_created_at, users.updated_at AS users_updated_at, users.is_active AS users_is_active 
FROM users 
WHERE users.email = %(email_1)s 
 LIMIT %(param_1)s
2024-10-09 16:05:16,677 - INFO - [generated in 0.00089s] {'email_1': 'user1111111@example.com', 'param_1': 1}
2024-10-09 16:05:16,683 - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-10-09 16:05:17,050 - INFO - INSERT INTO users (id, first_name, last_name, email, password, is_active) VALUES (%(id)s::UUID, %(first_name)s, %(last_name)s, %(email)s, %(password)s, %(is_active)s) RETURNING users.created_at, users.updated_at
2024-10-09 16:05:17,050 - INFO - [generated in 0.00059s] {'id': UUID('099ac529-6558-4ebe-8872-91e7ebfa0dc6'), 'first_name': 'string', 'last_name': 'string', 'email': 'user1111111@example.com', 'password': '$2b$12$Dg3JbQ8R1wY4AVf5lSkuQurf5nV604PWs8toLxRwRsaE8GeRMGdQO', 'is_active': False}
2024-10-09 16:05:17,052 - INFO - COMMIT
2024-10-09 16:05:17,059 - INFO - BEGIN (implicit)
2024-10-09 16:05:17,063 - INFO - SELECT users.id, users.first_name, users.last_name, users.email, users.password, users.created_at, users.updated_at, users.is_active 
FROM users 
WHERE users.id = %(pk_1)s::UUID
2024-10-09 16:05:17,063 - INFO - [generated in 0.00099s] {'pk_1': UUID('099ac529-6558-4ebe-8872-91e7ebfa0dc6')}
2024-10-09 16:05:17,068 - INFO - ROLLBACK
2024-10-09 16:05:50,731 - INFO - Shutting down
2024-10-09 16:05:50,832 - INFO - Waiting for application shutdown.
2024-10-09 16:05:50,834 - INFO - Application shutdown complete.
2024-10-09 16:05:50,835 - INFO - Finished server process [43073]
2024-10-09 16:06:03,622 - INFO - App started successfully!
2024-10-09 16:06:03,623 - INFO - Database connected successfully!
2024-10-09 16:06:03,623 - INFO - Started server process [43556]
2024-10-09 16:06:03,624 - INFO - Waiting for application startup.
2024-10-09 16:06:03,624 - INFO - Application startup complete.
2024-10-09 16:06:08,544 - INFO - BEGIN (implicit)
2024-10-09 16:06:08,552 - INFO - SELECT users.id AS users_id, users.first_name AS users_first_name, users.last_name AS users_last_name, users.email AS users_email, users.password AS users_password, users.created_at AS users_created_at, users.updated_at AS users_updated_at, users.is_active AS users_is_active 
FROM users 
WHERE users.email = %(email_1)s 
 LIMIT %(param_1)s
2024-10-09 16:06:08,552 - INFO - [generated in 0.00128s] {'email_1': 'samwakuedd244332982833239@gmail.com', 'param_1': 1}
2024-10-09 16:06:08,557 - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-10-09 16:06:09,025 - INFO - INSERT INTO users (id, first_name, last_name, email, password, is_active) VALUES (%(id)s::UUID, %(first_name)s, %(last_name)s, %(email)s, %(password)s, %(is_active)s) RETURNING users.created_at, users.updated_at
2024-10-09 16:06:09,027 - INFO - [generated in 0.00180s] {'id': UUID('d3f16ae0-7e50-45b2-a920-cdfecdeb8e8a'), 'first_name': 'Samuel22', 'last_name': 'Wakumelo22', 'email': 'samwakuedd244332982833239@gmail.com', 'password': '$2b$12$giDcxK5as1t89DG6IPN/BeP3J60YTm7xQlC1UpNoktVqyEcH64VLu', 'is_active': False}
2024-10-09 16:06:09,030 - INFO - COMMIT
2024-10-09 16:06:09,043 - INFO - BEGIN (implicit)
2024-10-09 16:06:09,046 - INFO - SELECT users.id, users.first_name, users.last_name, users.email, users.password, users.created_at, users.updated_at, users.is_active 
FROM users 
WHERE users.id = %(pk_1)s::UUID
2024-10-09 16:06:09,046 - INFO - [generated in 0.00084s] {'pk_1': UUID('d3f16ae0-7e50-45b2-a920-cdfecdeb8e8a')}
2024-10-09 16:06:09,051 - INFO - ROLLBACK
2024-10-09 16:09:25,068 - INFO - Shutting down
2024-10-09 16:09:25,170 - INFO - Waiting for application shutdown.
2024-10-09 16:09:25,171 - INFO - Application shutdown complete.
2024-10-09 16:09:25,172 - INFO - Finished server process [43556]
2024-10-10 05:16:14,281 - INFO - App started successfully!
2024-10-10 05:16:14,283 - INFO - Database connected successfully!
2024-10-10 05:16:14,284 - INFO - Started server process [18727]
2024-10-10 05:16:14,285 - INFO - Waiting for application startup.
2024-10-10 05:16:14,285 - INFO - Application startup complete.
2024-10-10 05:45:24,195 - INFO - Shutting down
2024-10-10 05:45:24,295 - INFO - Waiting for application shutdown.
2024-10-10 05:45:24,296 - INFO - Application shutdown complete.
2024-10-10 05:45:24,296 - INFO - Finished server process [18727]
