2024-10-09 15:18:10,144 - INFO - App started successfully!
2024-10-09 15:18:10,145 - INFO - Database connected successfully!
2024-10-09 15:18:10,146 - INFO - Started server process [36936]
2024-10-09 15:18:10,146 - INFO - Waiting for application startup.
2024-10-09 15:18:10,147 - INFO - Application startup complete.
2024-10-09 15:24:31,069 - INFO - App started successfully!
2024-10-09 15:24:31,071 - INFO - Database connected successfully!
2024-10-09 15:24:31,071 - INFO - Started server process [37892]
2024-10-09 15:24:31,072 - INFO - Waiting for application startup.
2024-10-09 15:24:31,072 - INFO - Application startup complete.
2024-10-09 15:24:34,704 - INFO - Shutting down
2024-10-09 15:24:34,807 - INFO - Waiting for application shutdown.
2024-10-09 15:24:34,808 - INFO - Application shutdown complete.
2024-10-09 15:24:34,808 - INFO - Finished server process [37892]
2024-10-09 15:24:40,714 - INFO - App started successfully!
2024-10-09 15:24:40,715 - INFO - Database connected successfully!
2024-10-09 15:24:40,716 - INFO - Started server process [37951]
2024-10-09 15:24:40,716 - INFO - Waiting for application startup.
2024-10-09 15:24:40,717 - INFO - Application startup complete.
2024-10-09 15:24:44,433 - INFO - Shutting down
2024-10-09 15:24:44,534 - INFO - Waiting for application shutdown.
2024-10-09 15:24:44,534 - INFO - Application shutdown complete.
2024-10-09 15:24:44,535 - INFO - Finished server process [37951]
2024-10-09 15:24:46,623 - INFO - App started successfully!
2024-10-09 15:24:46,625 - INFO - Database connected successfully!
2024-10-09 15:24:46,625 - INFO - Started server process [37984]
2024-10-09 15:24:46,625 - INFO - Waiting for application startup.
2024-10-09 15:24:46,626 - INFO - Application startup complete.
2024-10-09 15:25:29,506 - INFO - Shutting down
2024-10-09 15:25:29,607 - INFO - Waiting for application shutdown.
2024-10-09 15:25:29,608 - INFO - Application shutdown complete.
2024-10-09 15:25:29,608 - INFO - Finished server process [37984]
2024-10-09 15:25:34,750 - INFO - App started successfully!
2024-10-09 15:25:34,752 - INFO - Database connected successfully!
2024-10-09 15:25:34,752 - INFO - Started server process [38086]
2024-10-09 15:25:34,753 - INFO - Waiting for application startup.
2024-10-09 15:25:34,753 - INFO - Application startup complete.
2024-10-09 15:30:33,336 - INFO - Shutting down
2024-10-09 15:30:33,438 - INFO - Waiting for application shutdown.
2024-10-09 15:30:33,439 - INFO - Application shutdown complete.
2024-10-09 15:30:33,439 - INFO - Finished server process [38086]
2024-10-09 15:30:42,391 - INFO - App started successfully!
2024-10-09 15:30:42,393 - INFO - Database connected successfully!
2024-10-09 15:30:42,393 - INFO - Started server process [38827]
2024-10-09 15:30:42,394 - INFO - Waiting for application startup.
2024-10-09 15:30:42,395 - INFO - Application startup complete.
2024-10-09 15:30:47,114 - INFO - Shutting down
2024-10-09 15:30:47,215 - INFO - Waiting for application shutdown.
2024-10-09 15:30:47,216 - INFO - Application shutdown complete.
2024-10-09 15:30:47,217 - INFO - Finished server process [38827]
2024-10-09 15:30:49,543 - INFO - App started successfully!
2024-10-09 15:30:49,545 - INFO - Database connected successfully!
2024-10-09 15:30:49,546 - INFO - Started server process [38863]
2024-10-09 15:30:49,546 - INFO - Waiting for application startup.
2024-10-09 15:30:49,547 - INFO - Application startup complete.
2024-10-09 15:31:16,378 - INFO - Shutting down
2024-10-09 15:31:16,480 - INFO - Waiting for application shutdown.
2024-10-09 15:31:16,481 - INFO - Application shutdown complete.
2024-10-09 15:31:16,481 - INFO - Finished server process [38863]
2024-10-09 15:31:19,262 - INFO - App started successfully!
2024-10-09 15:31:19,264 - INFO - Database connected successfully!
2024-10-09 15:31:19,264 - INFO - Started server process [38966]
2024-10-09 15:31:19,265 - INFO - Waiting for application startup.
2024-10-09 15:31:19,265 - INFO - Application startup complete.
2024-10-09 15:31:20,877 - INFO - Shutting down
2024-10-09 15:31:20,977 - INFO - Waiting for application shutdown.
2024-10-09 15:31:20,978 - INFO - Application shutdown complete.
2024-10-09 15:31:20,979 - INFO - Finished server process [38966]
2024-10-09 15:31:23,881 - INFO - App started successfully!
2024-10-09 15:31:23,883 - INFO - Database connected successfully!
2024-10-09 15:31:23,884 - INFO - Started server process [38996]
2024-10-09 15:31:23,885 - INFO - Waiting for application startup.
2024-10-09 15:31:23,888 - INFO - Application startup complete.
2024-10-09 15:31:25,299 - INFO - Shutting down
2024-10-09 15:31:25,399 - INFO - Waiting for application shutdown.
2024-10-09 15:31:25,400 - INFO - Application shutdown complete.
2024-10-09 15:31:25,401 - INFO - Finished server process [38996]
2024-10-09 15:31:27,719 - INFO - App started successfully!
2024-10-09 15:31:27,721 - INFO - Database connected successfully!
2024-10-09 15:31:27,721 - INFO - Started server process [39028]
2024-10-09 15:31:27,721 - INFO - Waiting for application startup.
2024-10-09 15:31:27,722 - INFO - Application startup complete.
2024-10-09 15:31:33,450 - INFO - Shutting down
2024-10-09 15:31:33,551 - INFO - Waiting for application shutdown.
2024-10-09 15:31:33,551 - INFO - Application shutdown complete.
2024-10-09 15:31:33,552 - INFO - Finished server process [39028]
2024-10-09 15:31:36,208 - INFO - App started successfully!
2024-10-09 15:31:36,210 - INFO - Database connected successfully!
2024-10-09 15:31:36,211 - INFO - Started server process [39087]
2024-10-09 15:31:36,211 - INFO - Waiting for application startup.
2024-10-09 15:31:36,212 - INFO - Application startup complete.
2024-10-09 15:31:44,647 - INFO - Shutting down
2024-10-09 15:31:44,747 - INFO - Waiting for application shutdown.
2024-10-09 15:31:44,748 - INFO - Application shutdown complete.
2024-10-09 15:31:44,748 - INFO - Finished server process [39087]
2024-10-09 15:31:47,586 - INFO - App started successfully!
2024-10-09 15:31:47,588 - INFO - Database connected successfully!
2024-10-09 15:31:47,589 - INFO - Started server process [39130]
2024-10-09 15:31:47,589 - INFO - Waiting for application startup.
2024-10-09 15:31:47,590 - INFO - Application startup complete.
2024-10-09 15:31:49,892 - INFO - App started successfully!
2024-10-09 15:31:49,894 - INFO - Database connected successfully!
2024-10-09 15:31:49,895 - INFO - Started server process [39157]
2024-10-09 15:31:49,895 - INFO - Waiting for application startup.
2024-10-09 15:31:49,896 - INFO - Application startup complete.
2024-10-09 15:31:55,319 - INFO - Shutting down
2024-10-09 15:31:55,420 - INFO - Waiting for application shutdown.
2024-10-09 15:31:55,421 - INFO - Application shutdown complete.
2024-10-09 15:31:55,422 - INFO - Finished server process [39157]
2024-10-09 15:31:58,694 - INFO - App started successfully!
2024-10-09 15:31:58,695 - INFO - Database connected successfully!
2024-10-09 15:31:58,696 - INFO - Started server process [39190]
2024-10-09 15:31:58,696 - INFO - Waiting for application startup.
2024-10-09 15:31:58,697 - INFO - Application startup complete.
2024-10-09 15:32:01,042 - INFO - App started successfully!
2024-10-09 15:32:01,044 - INFO - Database connected successfully!
2024-10-09 15:32:01,044 - INFO - Started server process [39219]
2024-10-09 15:32:01,045 - INFO - Waiting for application startup.
2024-10-09 15:32:01,046 - INFO - Application startup complete.
2024-10-09 15:32:10,887 - INFO - Shutting down
2024-10-09 15:32:10,987 - INFO - Waiting for application shutdown.
2024-10-09 15:32:10,988 - INFO - Application shutdown complete.
2024-10-09 15:32:10,989 - INFO - Finished server process [39219]
2024-10-09 15:32:46,071 - INFO - App started successfully!
2024-10-09 15:32:46,073 - INFO - Database connected successfully!
2024-10-09 15:32:46,073 - INFO - Started server process [39352]
2024-10-09 15:32:46,073 - INFO - Waiting for application startup.
2024-10-09 15:32:46,074 - INFO - Application startup complete.
2024-10-09 15:32:48,419 - INFO - App started successfully!
2024-10-09 15:32:48,421 - INFO - Database connected successfully!
2024-10-09 15:32:48,422 - INFO - Started server process [39382]
2024-10-09 15:32:48,422 - INFO - Waiting for application startup.
2024-10-09 15:32:48,423 - INFO - Application startup complete.
2024-10-09 15:33:29,053 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/terminalnator/Client_portal/app/routers/user_routes.py", line 15, in signup_endpoint
    return await signup(user)
TypeError: signup() missing 1 required positional argument: 'user'
2024-10-09 15:34:00,489 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/terminalnator/Client_portal/app/routers/user_routes.py", line 15, in signup_endpoint
    return await signup(user)
TypeError: signup() missing 1 required positional argument: 'user'
2024-10-09 15:39:42,294 - INFO - Shutting down
2024-10-09 15:39:42,395 - INFO - Waiting for application shutdown.
2024-10-09 15:39:42,396 - INFO - Application shutdown complete.
2024-10-09 15:39:42,396 - INFO - Finished server process [39382]
2024-10-09 15:39:59,485 - INFO - App started successfully!
2024-10-09 15:39:59,486 - INFO - Database connected successfully!
2024-10-09 15:39:59,487 - INFO - Started server process [39923]
2024-10-09 15:39:59,487 - INFO - Waiting for application startup.
2024-10-09 15:39:59,488 - INFO - Application startup complete.
2024-10-09 15:40:47,127 - INFO - BEGIN (implicit)
2024-10-09 15:40:47,132 - INFO - SELECT users.id AS users_id, users.first_name AS users_first_name, users.last_name AS users_last_name, users.email AS users_email, users.password AS users_password, users.created_at AS users_created_at, users.updated_at AS users_updated_at, users.is_active AS users_is_active 
FROM users 
WHERE users.email = %(email_1)s 
 LIMIT %(param_1)s
2024-10-09 15:40:47,133 - INFO - [generated in 0.00113s] {'email_1': 'user@example.com', 'param_1': 1}
2024-10-09 15:40:47,154 - INFO - ROLLBACK
2024-10-09 15:40:58,156 - INFO - BEGIN (implicit)
2024-10-09 15:40:58,159 - INFO - SELECT users.id AS users_id, users.first_name AS users_first_name, users.last_name AS users_last_name, users.email AS users_email, users.password AS users_password, users.created_at AS users_created_at, users.updated_at AS users_updated_at, users.is_active AS users_is_active 
FROM users 
WHERE users.email = %(email_1)s 
 LIMIT %(param_1)s
2024-10-09 15:40:58,161 - INFO - [cached since 11.03s ago] {'email_1': 'user22@example.com', 'param_1': 1}
2024-10-09 15:40:58,170 - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-10-09 15:40:58,532 - INFO - INSERT INTO users (id, first_name, last_name, email, password, is_active) VALUES (%(id)s::UUID, %(first_name)s, %(last_name)s, %(email)s, %(password)s, %(is_active)s) RETURNING users.created_at, users.updated_at
2024-10-09 15:40:58,532 - INFO - [generated in 0.00047s] {'id': UUID('9c6f6d94-175e-449d-9509-85fc6fdd3418'), 'first_name': 'string', 'last_name': 'string', 'email': 'user22@example.com', 'password': '$2b$12$Gu49TkEkCLmmDYZS3fM3tOCE8MkoTJZOgE9D6rL.uZi39ArmNelZe', 'is_active': False}
2024-10-09 15:40:58,537 - INFO - COMMIT
2024-10-09 15:40:58,548 - INFO - BEGIN (implicit)
2024-10-09 15:40:58,551 - INFO - SELECT users.id, users.first_name, users.last_name, users.email, users.password, users.created_at, users.updated_at, users.is_active 
FROM users 
WHERE users.id = %(pk_1)s::UUID
2024-10-09 15:40:58,551 - INFO - [generated in 0.00042s] {'pk_1': UUID('9c6f6d94-175e-449d-9509-85fc6fdd3418')}
2024-10-09 15:40:59,015 - INFO - ROLLBACK
2024-10-09 15:40:59,018 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 500, in _create_connection
    transport, _ = await asyncio.wait_for(connect_coro, timeout=self.timeout)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1036, in create_connection
    infos = await self._ensure_resolved(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1418, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
  File "/usr/lib/python3.10/asyncio/base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/connection.py", line 45, in _configure_connection
    await self.session.connect()
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 449, in connect
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 446, in connect
    response = await self._create_connection()
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 506, in _create_connection
    raise SMTPConnectError(
aiosmtplib.errors.SMTPConnectError: Error connecting to smtp.example.com on port 587: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/terminalnator/Client_portal/app/routers/user_routes.py", line 15, in signup_endpoint
    return await signup(db, user)
  File "/home/terminalnator/Client_portal/app/controllers/user_controller.py", line 26, in signup
    await send_verification_email(user.email, verification_token)
  File "/home/terminalnator/Client_portal/app/core/email.py", line 33, in send_verification_email
    await fm.send_message(message)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/fastmail.py", line 109, in send_message
    async with Connection(self.config) as session:
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/connection.py", line 23, in __aenter__
    await self._configure_connection()
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/connection.py", line 53, in _configure_connection
    raise ConnectionErrors(
fastapi_mail.errors.ConnectionErrors: Exception raised Error connecting to smtp.example.com on port 587: [Errno -2] Name or service not known, check your credentials or email service configuration
2024-10-09 15:46:01,556 - INFO - Shutting down
2024-10-09 15:46:01,657 - INFO - Waiting for application shutdown.
2024-10-09 15:46:01,658 - INFO - Application shutdown complete.
2024-10-09 15:46:01,658 - INFO - Finished server process [39923]
2024-10-09 15:46:11,271 - INFO - App started successfully!
2024-10-09 15:46:11,272 - INFO - Database connected successfully!
2024-10-09 15:46:11,273 - INFO - Started server process [40409]
2024-10-09 15:46:11,273 - INFO - Waiting for application startup.
2024-10-09 15:46:11,274 - INFO - Application startup complete.
2024-10-09 15:46:42,906 - INFO - BEGIN (implicit)
2024-10-09 15:46:42,914 - INFO - SELECT users.id AS users_id, users.first_name AS users_first_name, users.last_name AS users_last_name, users.email AS users_email, users.password AS users_password, users.created_at AS users_created_at, users.updated_at AS users_updated_at, users.is_active AS users_is_active 
FROM users 
WHERE users.email = %(email_1)s 
 LIMIT %(param_1)s
2024-10-09 15:46:42,915 - INFO - [generated in 0.00189s] {'email_1': 'user3321@example.com', 'param_1': 1}
2024-10-09 15:46:42,920 - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-10-09 15:46:43,284 - INFO - INSERT INTO users (id, first_name, last_name, email, password, is_active) VALUES (%(id)s::UUID, %(first_name)s, %(last_name)s, %(email)s, %(password)s, %(is_active)s) RETURNING users.created_at, users.updated_at
2024-10-09 15:46:43,285 - INFO - [generated in 0.00059s] {'id': UUID('1440186d-9ef2-4ee0-ba02-8d94472f17dd'), 'first_name': 'string', 'last_name': 'string', 'email': 'user3321@example.com', 'password': '$2b$12$aBGkgO6H9zahOvxrANg2iee/JbqijOeLNjRSUF3bsPSFvR.nyTgYS', 'is_active': False}
2024-10-09 15:46:43,287 - INFO - COMMIT
2024-10-09 15:46:43,292 - INFO - BEGIN (implicit)
2024-10-09 15:46:43,295 - INFO - SELECT users.id, users.first_name, users.last_name, users.email, users.password, users.created_at, users.updated_at, users.is_active 
FROM users 
WHERE users.id = %(pk_1)s::UUID
2024-10-09 15:46:43,296 - INFO - [generated in 0.00086s] {'pk_1': UUID('1440186d-9ef2-4ee0-ba02-8d94472f17dd')}
2024-10-09 15:46:43,317 - INFO - ROLLBACK
2024-10-09 15:46:43,320 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 500, in _create_connection
    transport, _ = await asyncio.wait_for(connect_coro, timeout=self.timeout)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1036, in create_connection
    infos = await self._ensure_resolved(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1418, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
  File "/usr/lib/python3.10/asyncio/base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/connection.py", line 45, in _configure_connection
    await self.session.connect()
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 449, in connect
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 446, in connect
    response = await self._create_connection()
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 506, in _create_connection
    raise SMTPConnectError(
aiosmtplib.errors.SMTPConnectError: Error connecting to smtp.example.com on port 587: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/terminalnator/Client_portal/app/routers/user_routes.py", line 15, in signup_endpoint
    return await signup(db, user)
  File "/home/terminalnator/Client_portal/app/controllers/user_controller.py", line 26, in signup
  File "/home/terminalnator/Client_portal/app/core/email.py", line 33, in send_verification_email
    await fm.send_message(message)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/fastmail.py", line 109, in send_message
    async with Connection(self.config) as session:
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/connection.py", line 23, in __aenter__
    await self._configure_connection()
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/connection.py", line 53, in _configure_connection
    raise ConnectionErrors(
fastapi_mail.errors.ConnectionErrors: Exception raised Error connecting to smtp.example.com on port 587: [Errno -2] Name or service not known, check your credentials or email service configuration
2024-10-09 15:47:52,510 - INFO - Shutting down
2024-10-09 15:47:52,611 - INFO - Waiting for application shutdown.
2024-10-09 15:47:52,612 - INFO - Application shutdown complete.
2024-10-09 15:47:52,613 - INFO - Finished server process [40409]
2024-10-09 15:48:41,145 - INFO - App started successfully!
2024-10-09 15:48:41,146 - INFO - Database connected successfully!
2024-10-09 15:48:41,147 - INFO - Started server process [40801]
2024-10-09 15:48:41,147 - INFO - Waiting for application startup.
2024-10-09 15:48:41,148 - INFO - Application startup complete.
2024-10-09 15:48:43,960 - INFO - Shutting down
2024-10-09 15:48:44,061 - INFO - Waiting for application shutdown.
2024-10-09 15:48:44,063 - INFO - Application shutdown complete.
2024-10-09 15:48:44,063 - INFO - Finished server process [40801]
2024-10-09 15:48:49,153 - INFO - App started successfully!
2024-10-09 15:48:49,154 - INFO - Database connected successfully!
2024-10-09 15:48:49,154 - INFO - Started server process [40845]
2024-10-09 15:48:49,155 - INFO - Waiting for application startup.
2024-10-09 15:48:49,155 - INFO - Application startup complete.
2024-10-09 15:48:57,712 - INFO - BEGIN (implicit)
2024-10-09 15:48:57,716 - INFO - SELECT users.id AS users_id, users.first_name AS users_first_name, users.last_name AS users_last_name, users.email AS users_email, users.password AS users_password, users.created_at AS users_created_at, users.updated_at AS users_updated_at, users.is_active AS users_is_active 
FROM users 
WHERE users.email = %(email_1)s 
 LIMIT %(param_1)s
2024-10-09 15:48:57,717 - INFO - [generated in 0.00066s] {'email_1': 'user3321@example.com', 'param_1': 1}
2024-10-09 15:48:57,723 - INFO - ROLLBACK
2024-10-09 15:49:05,275 - INFO - BEGIN (implicit)
2024-10-09 15:49:05,276 - INFO - SELECT users.id AS users_id, users.first_name AS users_first_name, users.last_name AS users_last_name, users.email AS users_email, users.password AS users_password, users.created_at AS users_created_at, users.updated_at AS users_updated_at, users.is_active AS users_is_active 
FROM users 
WHERE users.email = %(email_1)s 
 LIMIT %(param_1)s
2024-10-09 15:49:05,276 - INFO - [cached since 7.56s ago] {'email_1': 'user332g1@example.com', 'param_1': 1}
2024-10-09 15:49:05,280 - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-10-09 15:49:05,659 - INFO - INSERT INTO users (id, first_name, last_name, email, password, is_active) VALUES (%(id)s::UUID, %(first_name)s, %(last_name)s, %(email)s, %(password)s, %(is_active)s) RETURNING users.created_at, users.updated_at
2024-10-09 15:49:05,659 - INFO - [generated in 0.00052s] {'id': UUID('a8a54b19-ac07-42b2-aada-e9785d04f6b0'), 'first_name': 'string', 'last_name': 'string', 'email': 'user332g1@example.com', 'password': '$2b$12$hBspaJwRbw2DqO58nXtFgOOqW5bGhk3uF9rFvDdEg6AoK.ue1T4qy', 'is_active': False}
2024-10-09 15:49:05,661 - INFO - COMMIT
2024-10-09 15:49:05,670 - INFO - BEGIN (implicit)
2024-10-09 15:49:05,672 - INFO - SELECT users.id, users.first_name, users.last_name, users.email, users.password, users.created_at, users.updated_at, users.is_active 
FROM users 
WHERE users.id = %(pk_1)s::UUID
2024-10-09 15:49:05,673 - INFO - [generated in 0.00048s] {'pk_1': UUID('a8a54b19-ac07-42b2-aada-e9785d04f6b0')}
2024-10-09 15:49:05,675 - INFO - ROLLBACK
2024-10-09 15:49:05,678 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/terminalnator/Client_portal/app/routers/user_routes.py", line 15, in signup_endpoint
    return await signup(db, user)
TypeError: object str can't be used in 'await' expression
2024-10-09 15:51:12,521 - INFO - Shutting down
2024-10-09 15:51:12,622 - INFO - Waiting for application shutdown.
2024-10-09 15:51:12,623 - INFO - Application shutdown complete.
2024-10-09 15:51:12,623 - INFO - Finished server process [40845]
2024-10-09 15:51:14,869 - INFO - App started successfully!
2024-10-09 15:51:14,870 - INFO - Database connected successfully!
2024-10-09 15:51:14,871 - INFO - Started server process [41170]
2024-10-09 15:51:14,871 - INFO - Waiting for application startup.
2024-10-09 15:51:14,872 - INFO - Application startup complete.
2024-10-09 15:51:24,902 - INFO - BEGIN (implicit)
2024-10-09 15:51:24,913 - INFO - SELECT users.id AS users_id, users.first_name AS users_first_name, users.last_name AS users_last_name, users.email AS users_email, users.password AS users_password, users.created_at AS users_created_at, users.updated_at AS users_updated_at, users.is_active AS users_is_active 
FROM users 
WHERE users.email = %(email_1)s 
 LIMIT %(param_1)s
2024-10-09 15:51:24,914 - INFO - [generated in 0.00102s] {'email_1': 'user37732g1@example.com', 'param_1': 1}
2024-10-09 15:51:24,921 - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-10-09 15:51:25,303 - INFO - INSERT INTO users (id, first_name, last_name, email, password, is_active) VALUES (%(id)s::UUID, %(first_name)s, %(last_name)s, %(email)s, %(password)s, %(is_active)s) RETURNING users.created_at, users.updated_at
2024-10-09 15:51:25,303 - INFO - [generated in 0.00073s] {'id': UUID('fabad994-75df-40b8-85df-ce4b7ce8cd42'), 'first_name': 'string', 'last_name': 'string', 'email': 'user37732g1@example.com', 'password': '$2b$12$xjS53ouAeZhdMbuOzVI2WOfCWHzBPzz.Klb/05REshvZknR.t.Yhi', 'is_active': False}
2024-10-09 15:51:25,305 - INFO - COMMIT
2024-10-09 15:51:25,310 - INFO - BEGIN (implicit)
2024-10-09 15:51:25,313 - INFO - SELECT users.id, users.first_name, users.last_name, users.email, users.password, users.created_at, users.updated_at, users.is_active 
FROM users 
WHERE users.id = %(pk_1)s::UUID
2024-10-09 15:51:25,314 - INFO - [generated in 0.00066s] {'pk_1': UUID('fabad994-75df-40b8-85df-ce4b7ce8cd42')}
2024-10-09 15:51:25,318 - INFO - ROLLBACK
2024-10-09 15:51:48,543 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/terminalnator/Client_portal/app/routers/user_routes.py", line 22, in signin_endpoint
    return await signup(user)
TypeError: signup() missing 1 required positional argument: 'user'
2024-10-09 15:52:06,808 - INFO - Shutting down
2024-10-09 15:52:06,909 - INFO - Waiting for application shutdown.
2024-10-09 15:52:06,910 - INFO - Application shutdown complete.
2024-10-09 15:52:06,910 - INFO - Finished server process [41170]
2024-10-09 15:52:09,041 - INFO - App started successfully!
2024-10-09 15:52:09,042 - INFO - Database connected successfully!
2024-10-09 15:52:09,043 - INFO - Started server process [41340]
2024-10-09 15:52:09,043 - INFO - Waiting for application startup.
2024-10-09 15:52:09,044 - INFO - Application startup complete.
2024-10-09 15:52:16,789 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/terminalnator/Client_portal/app/routers/user_routes.py", line 22, in signin_endpoint
    return await signup(user)
TypeError: signup() missing 1 required positional argument: 'user'
2024-10-09 15:53:01,189 - INFO - Shutting down
2024-10-09 15:53:01,290 - INFO - Waiting for application shutdown.
2024-10-09 15:53:01,291 - INFO - Application shutdown complete.
2024-10-09 15:53:01,292 - INFO - Finished server process [41340]
2024-10-09 15:53:03,651 - INFO - App started successfully!
2024-10-09 15:53:03,652 - INFO - Database connected successfully!
2024-10-09 15:53:03,653 - INFO - Started server process [41438]
2024-10-09 15:53:03,654 - INFO - Waiting for application startup.
2024-10-09 15:53:03,654 - INFO - Application startup complete.
2024-10-09 15:53:08,075 - INFO - Shutting down
2024-10-09 15:53:08,176 - INFO - Waiting for application shutdown.
2024-10-09 15:53:08,177 - INFO - Application shutdown complete.
2024-10-09 15:53:08,178 - INFO - Finished server process [41438]
2024-10-09 15:54:08,189 - INFO - App started successfully!
2024-10-09 15:54:08,191 - INFO - Database connected successfully!
2024-10-09 15:54:08,195 - INFO - Started server process [41565]
2024-10-09 15:54:08,195 - INFO - Waiting for application startup.
2024-10-09 15:54:08,196 - INFO - Application startup complete.
2024-10-09 15:54:08,297 - INFO - Shutting down
2024-10-09 15:54:08,398 - INFO - Waiting for application shutdown.
2024-10-09 15:54:08,399 - INFO - Application shutdown complete.
2024-10-09 15:54:08,400 - INFO - Finished server process [41565]
2024-10-09 15:54:13,983 - INFO - App started successfully!
2024-10-09 15:54:13,984 - INFO - Database connected successfully!
2024-10-09 15:54:13,985 - INFO - Started server process [41601]
2024-10-09 15:54:13,985 - INFO - Waiting for application startup.
2024-10-09 15:54:13,985 - INFO - Application startup complete.
2024-10-09 15:54:17,177 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/terminalnator/Client_portal/app/routers/user_routes.py", line 22, in signin_endpoint
    return await signup(user)
TypeError: signup() missing 1 required positional argument: 'user'
2024-10-09 15:55:15,262 - INFO - Shutting down
2024-10-09 15:55:15,363 - INFO - Waiting for application shutdown.
2024-10-09 15:55:15,364 - INFO - Application shutdown complete.
2024-10-09 15:55:15,364 - INFO - Finished server process [41601]
2024-10-09 15:55:17,816 - INFO - App started successfully!
2024-10-09 15:55:17,817 - INFO - Database connected successfully!
2024-10-09 15:55:17,818 - INFO - Started server process [41709]
2024-10-09 15:55:17,818 - INFO - Waiting for application startup.
2024-10-09 15:55:17,819 - INFO - Application startup complete.
2024-10-09 15:55:34,390 - INFO - Shutting down
2024-10-09 15:55:34,491 - INFO - Waiting for application shutdown.
2024-10-09 15:55:34,492 - INFO - Application shutdown complete.
2024-10-09 15:55:34,492 - INFO - Finished server process [41709]
2024-10-09 15:55:36,828 - INFO - App started successfully!
2024-10-09 15:55:36,830 - INFO - Database connected successfully!
2024-10-09 15:55:36,831 - INFO - Started server process [41789]
2024-10-09 15:55:36,831 - INFO - Waiting for application startup.
2024-10-09 15:55:36,832 - INFO - Application startup complete.
2024-10-09 15:55:51,387 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/terminalnator/Client_portal/app/routers/user_routes.py", line 22, in signin_endpoint
    return await signin(user)
TypeError: signin() missing 1 required positional argument: 'user'
2024-10-09 15:59:42,865 - INFO - Shutting down
2024-10-09 15:59:42,966 - INFO - Waiting for application shutdown.
2024-10-09 15:59:42,967 - INFO - Application shutdown complete.
2024-10-09 15:59:42,967 - INFO - Finished server process [41789]
2024-10-09 15:59:45,457 - INFO - App started successfully!
2024-10-09 15:59:45,459 - INFO - Database connected successfully!
2024-10-09 15:59:45,460 - INFO - Started server process [42058]
2024-10-09 15:59:45,460 - INFO - Waiting for application startup.
2024-10-09 15:59:45,461 - INFO - Application startup complete.
2024-10-09 15:59:59,022 - INFO - Shutting down
2024-10-09 15:59:59,123 - INFO - Waiting for application shutdown.
2024-10-09 15:59:59,124 - INFO - Application shutdown complete.
2024-10-09 15:59:59,124 - INFO - Finished server process [42058]
2024-10-09 16:01:17,377 - INFO - App started successfully!
2024-10-09 16:01:17,380 - INFO - Database connected successfully!
2024-10-09 16:01:17,381 - INFO - Started server process [42526]
2024-10-09 16:01:17,381 - INFO - Waiting for application startup.
2024-10-09 16:01:17,382 - INFO - Application startup complete.
2024-10-09 16:01:26,527 - INFO - Shutting down
2024-10-09 16:01:26,628 - INFO - Waiting for application shutdown.
2024-10-09 16:01:26,629 - INFO - Application shutdown complete.
2024-10-09 16:01:26,630 - INFO - Finished server process [42526]
2024-10-09 16:01:38,532 - INFO - App started successfully!
2024-10-09 16:01:38,536 - INFO - Database connected successfully!
2024-10-09 16:01:38,537 - INFO - Started server process [42667]
2024-10-09 16:01:38,537 - INFO - Waiting for application startup.
2024-10-09 16:01:38,538 - INFO - Application startup complete.
2024-10-09 16:02:29,144 - INFO - Shutting down
2024-10-09 16:02:29,245 - INFO - Waiting for application shutdown.
2024-10-09 16:02:29,245 - INFO - Application shutdown complete.
2024-10-09 16:02:29,246 - INFO - Finished server process [42667]
2024-10-09 16:02:31,383 - INFO - App started successfully!
2024-10-09 16:02:31,385 - INFO - Database connected successfully!
2024-10-09 16:02:31,386 - INFO - Started server process [42741]
2024-10-09 16:02:31,386 - INFO - Waiting for application startup.
2024-10-09 16:02:31,387 - INFO - Application startup complete.
2024-10-09 16:02:44,573 - INFO - BEGIN (implicit)
2024-10-09 16:02:44,580 - INFO - SELECT users.id AS users_id, users.first_name AS users_first_name, users.last_name AS users_last_name, users.email AS users_email, users.password AS users_password, users.created_at AS users_created_at, users.updated_at AS users_updated_at, users.is_active AS users_is_active 
FROM users 
WHERE users.email = %(email_1)s 
 LIMIT %(param_1)s
2024-10-09 16:02:44,580 - INFO - [generated in 0.00057s] {'email_1': 'string', 'param_1': 1}
2024-10-09 16:02:44,584 - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-10-09 16:02:44,926 - INFO - ROLLBACK
2024-10-09 16:04:22,237 - INFO - Shutting down
2024-10-09 16:04:22,339 - INFO - Waiting for application shutdown.
2024-10-09 16:04:22,340 - INFO - Application shutdown complete.
2024-10-09 16:04:22,341 - INFO - Finished server process [42741]
2024-10-09 16:04:27,105 - INFO - App started successfully!
2024-10-09 16:04:27,111 - INFO - Database connected successfully!
2024-10-09 16:04:27,111 - INFO - Started server process [43000]
2024-10-09 16:04:27,112 - INFO - Waiting for application startup.
2024-10-09 16:04:27,112 - INFO - Application startup complete.
2024-10-09 16:04:31,117 - INFO - App started successfully!
2024-10-09 16:04:31,120 - INFO - Database connected successfully!
2024-10-09 16:04:31,123 - INFO - Started server process [43038]
2024-10-09 16:04:31,124 - INFO - Waiting for application startup.
2024-10-09 16:04:31,124 - INFO - Application startup complete.
2024-10-09 16:04:31,730 - INFO - Shutting down
2024-10-09 16:04:31,831 - INFO - Waiting for application shutdown.
2024-10-09 16:04:31,832 - INFO - Application shutdown complete.
2024-10-09 16:04:31,832 - INFO - Finished server process [43038]
2024-10-09 16:04:33,925 - INFO - App started successfully!
2024-10-09 16:04:33,926 - INFO - Database connected successfully!
2024-10-09 16:04:33,927 - INFO - Started server process [43073]
2024-10-09 16:04:33,927 - INFO - Waiting for application startup.
2024-10-09 16:04:33,927 - INFO - Application startup complete.
2024-10-09 16:05:16,672 - INFO - BEGIN (implicit)
2024-10-09 16:05:16,676 - INFO - SELECT users.id AS users_id, users.first_name AS users_first_name, users.last_name AS users_last_name, users.email AS users_email, users.password AS users_password, users.created_at AS users_created_at, users.updated_at AS users_updated_at, users.is_active AS users_is_active 
FROM users 
WHERE users.email = %(email_1)s 
 LIMIT %(param_1)s
2024-10-09 16:05:16,677 - INFO - [generated in 0.00089s] {'email_1': 'user1111111@example.com', 'param_1': 1}
2024-10-09 16:05:16,683 - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-10-09 16:05:17,050 - INFO - INSERT INTO users (id, first_name, last_name, email, password, is_active) VALUES (%(id)s::UUID, %(first_name)s, %(last_name)s, %(email)s, %(password)s, %(is_active)s) RETURNING users.created_at, users.updated_at
2024-10-09 16:05:17,050 - INFO - [generated in 0.00059s] {'id': UUID('099ac529-6558-4ebe-8872-91e7ebfa0dc6'), 'first_name': 'string', 'last_name': 'string', 'email': 'user1111111@example.com', 'password': '$2b$12$Dg3JbQ8R1wY4AVf5lSkuQurf5nV604PWs8toLxRwRsaE8GeRMGdQO', 'is_active': False}
2024-10-09 16:05:17,052 - INFO - COMMIT
2024-10-09 16:05:17,059 - INFO - BEGIN (implicit)
2024-10-09 16:05:17,063 - INFO - SELECT users.id, users.first_name, users.last_name, users.email, users.password, users.created_at, users.updated_at, users.is_active 
FROM users 
WHERE users.id = %(pk_1)s::UUID
2024-10-09 16:05:17,063 - INFO - [generated in 0.00099s] {'pk_1': UUID('099ac529-6558-4ebe-8872-91e7ebfa0dc6')}
2024-10-09 16:05:17,068 - INFO - ROLLBACK
2024-10-09 16:05:50,731 - INFO - Shutting down
2024-10-09 16:05:50,832 - INFO - Waiting for application shutdown.
2024-10-09 16:05:50,834 - INFO - Application shutdown complete.
2024-10-09 16:05:50,835 - INFO - Finished server process [43073]
2024-10-09 16:06:03,622 - INFO - App started successfully!
2024-10-09 16:06:03,623 - INFO - Database connected successfully!
2024-10-09 16:06:03,623 - INFO - Started server process [43556]
2024-10-09 16:06:03,624 - INFO - Waiting for application startup.
2024-10-09 16:06:03,624 - INFO - Application startup complete.
2024-10-09 16:06:08,544 - INFO - BEGIN (implicit)
2024-10-09 16:06:08,552 - INFO - SELECT users.id AS users_id, users.first_name AS users_first_name, users.last_name AS users_last_name, users.email AS users_email, users.password AS users_password, users.created_at AS users_created_at, users.updated_at AS users_updated_at, users.is_active AS users_is_active 
FROM users 
WHERE users.email = %(email_1)s 
 LIMIT %(param_1)s
2024-10-09 16:06:08,552 - INFO - [generated in 0.00128s] {'email_1': 'samwakuedd244332982833239@gmail.com', 'param_1': 1}
2024-10-09 16:06:08,557 - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-10-09 16:06:09,025 - INFO - INSERT INTO users (id, first_name, last_name, email, password, is_active) VALUES (%(id)s::UUID, %(first_name)s, %(last_name)s, %(email)s, %(password)s, %(is_active)s) RETURNING users.created_at, users.updated_at
2024-10-09 16:06:09,027 - INFO - [generated in 0.00180s] {'id': UUID('d3f16ae0-7e50-45b2-a920-cdfecdeb8e8a'), 'first_name': 'Samuel22', 'last_name': 'Wakumelo22', 'email': 'samwakuedd244332982833239@gmail.com', 'password': '$2b$12$giDcxK5as1t89DG6IPN/BeP3J60YTm7xQlC1UpNoktVqyEcH64VLu', 'is_active': False}
2024-10-09 16:06:09,030 - INFO - COMMIT
2024-10-09 16:06:09,043 - INFO - BEGIN (implicit)
2024-10-09 16:06:09,046 - INFO - SELECT users.id, users.first_name, users.last_name, users.email, users.password, users.created_at, users.updated_at, users.is_active 
FROM users 
WHERE users.id = %(pk_1)s::UUID
2024-10-09 16:06:09,046 - INFO - [generated in 0.00084s] {'pk_1': UUID('d3f16ae0-7e50-45b2-a920-cdfecdeb8e8a')}
2024-10-09 16:06:09,051 - INFO - ROLLBACK
2024-10-09 16:09:25,068 - INFO - Shutting down
2024-10-09 16:09:25,170 - INFO - Waiting for application shutdown.
2024-10-09 16:09:25,171 - INFO - Application shutdown complete.
2024-10-09 16:09:25,172 - INFO - Finished server process [43556]
2024-10-10 05:16:14,281 - INFO - App started successfully!
2024-10-10 05:16:14,283 - INFO - Database connected successfully!
2024-10-10 05:16:14,284 - INFO - Started server process [18727]
2024-10-10 05:16:14,285 - INFO - Waiting for application startup.
2024-10-10 05:16:14,285 - INFO - Application startup complete.
2024-10-10 05:45:24,195 - INFO - Shutting down
2024-10-10 05:45:24,295 - INFO - Waiting for application shutdown.
2024-10-10 05:45:24,296 - INFO - Application shutdown complete.
2024-10-10 05:45:24,296 - INFO - Finished server process [18727]
2024-10-10 06:31:47,816 - INFO - App started successfully!
2024-10-10 06:31:47,817 - INFO - Database connected successfully!
2024-10-10 06:31:47,818 - INFO - Started server process [26502]
2024-10-10 06:31:47,818 - INFO - Waiting for application startup.
2024-10-10 06:31:47,818 - INFO - Application startup complete.
2024-10-10 06:32:31,438 - INFO - BEGIN (implicit)
2024-10-10 06:32:31,442 - INFO - SELECT users.id AS users_id, users.first_name AS users_first_name, users.last_name AS users_last_name, users.email AS users_email, users.password AS users_password, users.created_at AS users_created_at, users.updated_at AS users_updated_at, users.is_active AS users_is_active 
FROM users 
WHERE users.email = %(email_1)s 
 LIMIT %(param_1)s
2024-10-10 06:32:31,443 - INFO - [generated in 0.00047s] {'email_1': 'samwakuedd244332982833239@gmail.com', 'param_1': 1}
2024-10-10 06:32:31,463 - INFO - ROLLBACK
2024-10-10 06:32:50,418 - INFO - BEGIN (implicit)
2024-10-10 06:32:50,419 - INFO - SELECT users.id AS users_id, users.first_name AS users_first_name, users.last_name AS users_last_name, users.email AS users_email, users.password AS users_password, users.created_at AS users_created_at, users.updated_at AS users_updated_at, users.is_active AS users_is_active 
FROM users 
WHERE users.email = %(email_1)s 
 LIMIT %(param_1)s
2024-10-10 06:32:50,419 - INFO - [cached since 18.98s ago] {'email_1': 'samwakuedd2443332982833239@gmail.com', 'param_1': 1}
2024-10-10 06:32:50,427 - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-10-10 06:32:50,783 - INFO - INSERT INTO users (id, first_name, last_name, email, password, is_active) VALUES (%(id)s::UUID, %(first_name)s, %(last_name)s, %(email)s, %(password)s, %(is_active)s) RETURNING users.created_at, users.updated_at
2024-10-10 06:32:50,783 - INFO - [generated in 0.00051s] {'id': UUID('33fdb375-b757-4f1d-a534-1de2fae1ad96'), 'first_name': 'Samuel22', 'last_name': 'Wakumelo22', 'email': 'samwakuedd2443332982833239@gmail.com', 'password': '$2b$12$efXfYgLaqY9Ys1ImYMnQGeDOjQrOcndbTo3B9iTQk3YxCLjaoc1tK', 'is_active': False}
2024-10-10 06:32:50,787 - INFO - COMMIT
2024-10-10 06:32:50,797 - INFO - BEGIN (implicit)
2024-10-10 06:32:50,799 - INFO - SELECT users.id, users.first_name, users.last_name, users.email, users.password, users.created_at, users.updated_at, users.is_active 
FROM users 
WHERE users.id = %(pk_1)s::UUID
2024-10-10 06:32:50,799 - INFO - [generated in 0.00047s] {'pk_1': UUID('33fdb375-b757-4f1d-a534-1de2fae1ad96')}
2024-10-10 06:32:50,804 - INFO - ROLLBACK
2024-10-10 06:41:49,736 - INFO - Shutting down
2024-10-10 06:41:49,837 - INFO - Waiting for application shutdown.
2024-10-10 06:41:49,838 - INFO - Application shutdown complete.
2024-10-10 06:41:49,838 - INFO - Finished server process [26502]
2024-10-10 06:41:52,105 - INFO - App started successfully!
2024-10-10 06:41:52,108 - INFO - Database connected successfully!
2024-10-10 06:41:52,109 - INFO - Started server process [27412]
2024-10-10 06:41:52,109 - INFO - Waiting for application startup.
2024-10-10 06:41:52,110 - INFO - Application startup complete.
2024-10-10 06:41:55,224 - INFO - Shutting down
2024-10-10 06:41:55,325 - INFO - Waiting for application shutdown.
2024-10-10 06:41:55,326 - INFO - Application shutdown complete.
2024-10-10 06:41:55,326 - INFO - Finished server process [27412]
2024-10-10 06:41:57,228 - INFO - App started successfully!
2024-10-10 06:41:57,229 - INFO - Database connected successfully!
2024-10-10 06:41:57,230 - INFO - Started server process [27446]
2024-10-10 06:41:57,230 - INFO - Waiting for application startup.
2024-10-10 06:41:57,231 - INFO - Application startup complete.
2024-10-10 06:45:18,659 - INFO - Shutting down
2024-10-10 06:45:18,760 - INFO - Waiting for application shutdown.
2024-10-10 06:45:18,761 - INFO - Application shutdown complete.
2024-10-10 06:45:18,761 - INFO - Finished server process [27446]
2024-10-10 06:45:20,550 - INFO - App started successfully!
2024-10-10 06:45:20,553 - INFO - Database connected successfully!
2024-10-10 06:45:20,554 - INFO - Started server process [27575]
2024-10-10 06:45:20,554 - INFO - Waiting for application startup.
2024-10-10 06:45:20,554 - INFO - Application startup complete.
2024-10-10 06:45:21,560 - INFO - Shutting down
2024-10-10 06:45:21,661 - INFO - Waiting for application shutdown.
2024-10-10 06:45:21,662 - INFO - Application shutdown complete.
2024-10-10 06:45:21,663 - INFO - Finished server process [27575]
2024-10-10 06:45:23,570 - INFO - App started successfully!
2024-10-10 06:45:23,571 - INFO - Database connected successfully!
2024-10-10 06:45:23,572 - INFO - Started server process [27608]
2024-10-10 06:45:23,572 - INFO - Waiting for application startup.
2024-10-10 06:45:23,573 - INFO - Application startup complete.
2024-10-10 06:45:23,975 - INFO - Shutting down
2024-10-10 06:45:24,076 - INFO - Waiting for application shutdown.
2024-10-10 06:45:24,076 - INFO - Application shutdown complete.
2024-10-10 06:45:24,077 - INFO - Finished server process [27608]
2024-10-10 06:45:25,852 - INFO - App started successfully!
2024-10-10 06:45:25,853 - INFO - Database connected successfully!
2024-10-10 06:45:25,854 - INFO - Started server process [27615]
2024-10-10 06:45:25,854 - INFO - Waiting for application startup.
2024-10-10 06:45:25,854 - INFO - Application startup complete.
2024-10-10 06:45:30,384 - INFO - Shutting down
2024-10-10 06:45:30,484 - INFO - Waiting for application shutdown.
2024-10-10 06:45:30,485 - INFO - Application shutdown complete.
2024-10-10 06:45:30,485 - INFO - Finished server process [27615]
2024-10-10 06:45:32,283 - INFO - App started successfully!
2024-10-10 06:45:32,284 - INFO - Database connected successfully!
2024-10-10 06:45:32,286 - INFO - Started server process [27667]
2024-10-10 06:45:32,286 - INFO - Waiting for application startup.
2024-10-10 06:45:32,286 - INFO - Application startup complete.
2024-10-10 06:45:40,723 - INFO - Shutting down
2024-10-10 06:45:40,824 - INFO - Waiting for application shutdown.
2024-10-10 06:45:40,825 - INFO - Application shutdown complete.
2024-10-10 06:45:40,825 - INFO - Finished server process [27667]
2024-10-10 06:45:42,710 - INFO - App started successfully!
2024-10-10 06:45:42,711 - INFO - Database connected successfully!
2024-10-10 06:45:42,712 - INFO - Started server process [27717]
2024-10-10 06:45:42,712 - INFO - Waiting for application startup.
2024-10-10 06:45:42,712 - INFO - Application startup complete.
2024-10-10 06:45:46,433 - INFO - Shutting down
2024-10-10 06:45:46,534 - INFO - Waiting for application shutdown.
2024-10-10 06:45:46,534 - INFO - Application shutdown complete.
2024-10-10 06:45:46,535 - INFO - Finished server process [27717]
2024-10-10 06:45:48,494 - INFO - App started successfully!
2024-10-10 06:45:48,495 - INFO - Database connected successfully!
2024-10-10 06:45:48,496 - INFO - Started server process [27752]
2024-10-10 06:45:48,496 - INFO - Waiting for application startup.
2024-10-10 06:45:48,496 - INFO - Application startup complete.
2024-10-10 06:59:58,547 - INFO - Shutting down
2024-10-10 06:59:58,648 - INFO - Waiting for application shutdown.
2024-10-10 06:59:58,649 - INFO - Application shutdown complete.
2024-10-10 06:59:58,650 - INFO - Finished server process [27752]
2024-10-10 07:00:00,613 - INFO - App started successfully!
2024-10-10 07:00:00,614 - INFO - Database connected successfully!
2024-10-10 07:00:00,615 - INFO - Started server process [28134]
2024-10-10 07:00:00,615 - INFO - Waiting for application startup.
2024-10-10 07:00:00,615 - INFO - Application startup complete.
2024-10-10 07:08:48,696 - INFO - Shutting down
2024-10-10 07:08:48,797 - INFO - Waiting for application shutdown.
2024-10-10 07:08:48,798 - INFO - Application shutdown complete.
2024-10-10 07:08:48,799 - INFO - Finished server process [28134]
2024-10-10 07:08:50,543 - INFO - App started successfully!
2024-10-10 07:08:50,544 - INFO - Database connected successfully!
2024-10-10 07:08:50,544 - INFO - Started server process [28442]
2024-10-10 07:08:50,545 - INFO - Waiting for application startup.
2024-10-10 07:08:50,545 - INFO - Application startup complete.
2024-10-10 07:09:19,467 - INFO - Shutting down
2024-10-10 07:09:19,568 - INFO - Waiting for application shutdown.
2024-10-10 07:09:19,568 - INFO - Application shutdown complete.
2024-10-10 07:09:19,569 - INFO - Finished server process [28442]
2024-10-10 07:09:21,424 - INFO - App started successfully!
2024-10-10 07:09:21,425 - INFO - Database connected successfully!
2024-10-10 07:09:21,426 - INFO - Started server process [28520]
2024-10-10 07:09:21,426 - INFO - Waiting for application startup.
2024-10-10 07:09:21,426 - INFO - Application startup complete.
2024-10-10 07:09:27,955 - INFO - Shutting down
2024-10-10 07:09:28,056 - INFO - Waiting for application shutdown.
2024-10-10 07:09:28,057 - INFO - Application shutdown complete.
2024-10-10 07:09:28,057 - INFO - Finished server process [28520]
2024-10-10 07:09:30,794 - INFO - App started successfully!
2024-10-10 07:09:30,796 - INFO - Database connected successfully!
2024-10-10 07:09:30,796 - INFO - Started server process [28576]
2024-10-10 07:09:30,797 - INFO - Waiting for application startup.
2024-10-10 07:09:30,797 - INFO - Application startup complete.
2024-10-10 07:09:33,158 - INFO - App started successfully!
2024-10-10 07:09:33,160 - INFO - Database connected successfully!
2024-10-10 07:09:33,161 - INFO - Started server process [28593]
2024-10-10 07:09:33,161 - INFO - Waiting for application startup.
2024-10-10 07:09:33,162 - INFO - Application startup complete.
2024-10-10 07:09:35,690 - INFO - App started successfully!
2024-10-10 07:09:35,692 - INFO - Database connected successfully!
2024-10-10 07:09:35,692 - INFO - Started server process [28610]
2024-10-10 07:09:35,692 - INFO - Waiting for application startup.
2024-10-10 07:09:35,693 - INFO - Application startup complete.
2024-10-10 07:09:38,222 - INFO - App started successfully!
2024-10-10 07:09:38,226 - INFO - Database connected successfully!
2024-10-10 07:09:38,227 - INFO - Started server process [28630]
2024-10-10 07:09:38,228 - INFO - Waiting for application startup.
2024-10-10 07:09:38,229 - INFO - Application startup complete.
2024-10-10 07:09:40,139 - INFO - Shutting down
2024-10-10 07:09:40,240 - INFO - Waiting for application shutdown.
2024-10-10 07:09:40,241 - INFO - Application shutdown complete.
2024-10-10 07:09:40,243 - INFO - Finished server process [28630]
2024-10-10 07:09:42,433 - INFO - App started successfully!
2024-10-10 07:09:42,434 - INFO - Database connected successfully!
2024-10-10 07:09:42,435 - INFO - Started server process [28647]
2024-10-10 07:09:42,435 - INFO - Waiting for application startup.
2024-10-10 07:09:42,435 - INFO - Application startup complete.
2024-10-10 07:09:43,954 - INFO - App started successfully!
2024-10-10 07:09:43,956 - INFO - Database connected successfully!
2024-10-10 07:09:43,956 - INFO - Started server process [28678]
2024-10-10 07:09:43,956 - INFO - Waiting for application startup.
2024-10-10 07:09:43,957 - INFO - Application startup complete.
2024-10-10 07:09:48,383 - INFO - Shutting down
2024-10-10 07:09:48,484 - INFO - Waiting for application shutdown.
2024-10-10 07:09:48,485 - INFO - Application shutdown complete.
2024-10-10 07:09:48,485 - INFO - Finished server process [28678]
2024-10-10 07:09:50,670 - INFO - App started successfully!
2024-10-10 07:09:50,674 - INFO - Database connected successfully!
2024-10-10 07:09:50,674 - INFO - Started server process [28708]
2024-10-10 07:09:50,674 - INFO - Waiting for application startup.
2024-10-10 07:09:50,675 - INFO - Application startup complete.
2024-10-10 07:09:52,397 - INFO - App started successfully!
2024-10-10 07:09:52,399 - INFO - Database connected successfully!
2024-10-10 07:09:52,399 - INFO - Started server process [28725]
2024-10-10 07:09:52,399 - INFO - Waiting for application startup.
2024-10-10 07:09:52,400 - INFO - Application startup complete.
2024-10-10 07:09:54,081 - INFO - App started successfully!
2024-10-10 07:09:54,082 - INFO - Database connected successfully!
2024-10-10 07:09:54,083 - INFO - Started server process [28741]
2024-10-10 07:09:54,083 - INFO - Waiting for application startup.
2024-10-10 07:09:54,084 - INFO - Application startup complete.
2024-10-10 07:09:58,513 - INFO - Shutting down
2024-10-10 07:09:58,614 - INFO - Waiting for application shutdown.
2024-10-10 07:09:58,615 - INFO - Application shutdown complete.
2024-10-10 07:09:58,615 - INFO - Finished server process [28741]
2024-10-10 07:10:00,925 - INFO - App started successfully!
2024-10-10 07:10:00,927 - INFO - Database connected successfully!
2024-10-10 07:10:00,928 - INFO - Started server process [28774]
2024-10-10 07:10:00,929 - INFO - Waiting for application startup.
2024-10-10 07:10:00,930 - INFO - Application startup complete.
2024-10-10 07:10:03,628 - INFO - App started successfully!
2024-10-10 07:10:03,630 - INFO - Database connected successfully!
2024-10-10 07:10:03,631 - INFO - Started server process [28791]
2024-10-10 07:10:03,632 - INFO - Waiting for application startup.
2024-10-10 07:10:03,633 - INFO - Application startup complete.
2024-10-10 07:10:03,736 - INFO - Shutting down
2024-10-10 07:10:03,837 - INFO - Waiting for application shutdown.
2024-10-10 07:10:03,837 - INFO - Application shutdown complete.
2024-10-10 07:10:03,837 - INFO - Finished server process [28791]
2024-10-10 07:10:06,177 - INFO - App started successfully!
2024-10-10 07:10:06,178 - INFO - Database connected successfully!
2024-10-10 07:10:06,179 - INFO - Started server process [28806]
2024-10-10 07:10:06,179 - INFO - Waiting for application startup.
2024-10-10 07:10:06,179 - INFO - Application startup complete.
2024-10-10 07:10:08,099 - INFO - App started successfully!
2024-10-10 07:10:08,100 - INFO - Database connected successfully!
2024-10-10 07:10:08,101 - INFO - Started server process [28824]
2024-10-10 07:10:08,101 - INFO - Waiting for application startup.
2024-10-10 07:10:08,102 - INFO - Application startup complete.
2024-10-10 07:10:09,614 - INFO - App started successfully!
2024-10-10 07:10:09,615 - INFO - Database connected successfully!
2024-10-10 07:10:09,616 - INFO - Started server process [28842]
2024-10-10 07:10:09,616 - INFO - Waiting for application startup.
2024-10-10 07:10:09,616 - INFO - Application startup complete.
2024-10-10 07:10:11,222 - INFO - Shutting down
2024-10-10 07:10:11,323 - INFO - Waiting for application shutdown.
2024-10-10 07:10:11,324 - INFO - Application shutdown complete.
2024-10-10 07:10:11,325 - INFO - Finished server process [28842]
2024-10-10 07:10:13,523 - INFO - App started successfully!
2024-10-10 07:10:13,525 - INFO - Database connected successfully!
2024-10-10 07:10:13,527 - INFO - Started server process [28860]
2024-10-10 07:10:13,527 - INFO - Waiting for application startup.
2024-10-10 07:10:13,528 - INFO - Application startup complete.
2024-10-10 07:10:14,434 - INFO - Shutting down
2024-10-10 07:10:14,536 - INFO - Waiting for application shutdown.
2024-10-10 07:10:14,536 - INFO - Application shutdown complete.
2024-10-10 07:10:14,536 - INFO - Finished server process [28860]
2024-10-10 07:10:16,462 - INFO - App started successfully!
2024-10-10 07:10:16,463 - INFO - Database connected successfully!
2024-10-10 07:10:16,463 - INFO - Started server process [28877]
2024-10-10 07:10:16,464 - INFO - Waiting for application startup.
2024-10-10 07:10:16,464 - INFO - Application startup complete.
2024-10-10 07:10:18,594 - INFO - App started successfully!
2024-10-10 07:10:18,596 - INFO - Database connected successfully!
2024-10-10 07:10:18,597 - INFO - Started server process [28896]
2024-10-10 07:10:18,598 - INFO - Waiting for application startup.
2024-10-10 07:10:18,599 - INFO - Application startup complete.
2024-10-10 07:10:21,358 - INFO - App started successfully!
2024-10-10 07:10:21,360 - INFO - Database connected successfully!
2024-10-10 07:10:21,361 - INFO - Started server process [28913]
2024-10-10 07:10:21,361 - INFO - Waiting for application startup.
2024-10-10 07:10:21,362 - INFO - Application startup complete.
2024-10-10 07:10:25,683 - INFO - Shutting down
2024-10-10 07:10:25,784 - INFO - Waiting for application shutdown.
2024-10-10 07:10:25,785 - INFO - Application shutdown complete.
2024-10-10 07:10:25,785 - INFO - Finished server process [28913]
2024-10-10 07:10:27,414 - INFO - App started successfully!
2024-10-10 07:10:27,415 - INFO - Database connected successfully!
2024-10-10 07:10:27,416 - INFO - Started server process [28955]
2024-10-10 07:10:27,416 - INFO - Waiting for application startup.
2024-10-10 07:10:27,416 - INFO - Application startup complete.
2024-10-10 07:10:31,033 - INFO - Shutting down
2024-10-10 07:10:31,134 - INFO - Waiting for application shutdown.
2024-10-10 07:10:31,135 - INFO - Application shutdown complete.
2024-10-10 07:10:31,135 - INFO - Finished server process [28955]
2024-10-10 07:10:33,293 - INFO - App started successfully!
2024-10-10 07:10:33,294 - INFO - Database connected successfully!
2024-10-10 07:10:33,295 - INFO - Started server process [28985]
2024-10-10 07:10:33,295 - INFO - Waiting for application startup.
2024-10-10 07:10:33,295 - INFO - Application startup complete.
2024-10-10 07:10:36,312 - INFO - Shutting down
2024-10-10 07:10:36,413 - INFO - Waiting for application shutdown.
2024-10-10 07:10:36,414 - INFO - Application shutdown complete.
2024-10-10 07:10:36,415 - INFO - Finished server process [28985]
2024-10-10 07:10:38,043 - INFO - App started successfully!
2024-10-10 07:10:38,045 - INFO - Database connected successfully!
2024-10-10 07:10:38,046 - INFO - Started server process [29026]
2024-10-10 07:10:38,046 - INFO - Waiting for application startup.
2024-10-10 07:10:38,046 - INFO - Application startup complete.
2024-10-10 07:10:46,683 - INFO - Shutting down
2024-10-10 07:10:46,784 - INFO - Waiting for application shutdown.
2024-10-10 07:10:46,786 - INFO - Application shutdown complete.
2024-10-10 07:10:46,786 - INFO - Finished server process [29026]
2024-10-10 07:10:48,363 - INFO - App started successfully!
2024-10-10 07:10:48,364 - INFO - Database connected successfully!
2024-10-10 07:10:48,365 - INFO - Started server process [29070]
2024-10-10 07:10:48,365 - INFO - Waiting for application startup.
2024-10-10 07:10:48,365 - INFO - Application startup complete.
2024-10-10 07:11:14,884 - INFO - Shutting down
2024-10-10 07:11:14,985 - INFO - Waiting for application shutdown.
2024-10-10 07:11:14,986 - INFO - Application shutdown complete.
2024-10-10 07:11:14,986 - INFO - Finished server process [29070]
2024-10-10 07:11:17,052 - INFO - App started successfully!
2024-10-10 07:11:17,054 - INFO - Database connected successfully!
2024-10-10 07:11:17,056 - INFO - Started server process [29132]
2024-10-10 07:11:17,056 - INFO - Waiting for application startup.
2024-10-10 07:11:17,057 - INFO - Application startup complete.
2024-10-10 07:11:17,460 - INFO - Shutting down
2024-10-10 07:11:17,561 - INFO - Waiting for application shutdown.
2024-10-10 07:11:17,561 - INFO - Application shutdown complete.
2024-10-10 07:11:17,561 - INFO - Finished server process [29132]
2024-10-10 07:11:19,468 - INFO - App started successfully!
2024-10-10 07:11:19,470 - INFO - Database connected successfully!
2024-10-10 07:11:19,470 - INFO - Started server process [29164]
2024-10-10 07:11:19,471 - INFO - Waiting for application startup.
2024-10-10 07:11:19,471 - INFO - Application startup complete.
2024-10-10 07:11:23,591 - INFO - Shutting down
2024-10-10 07:11:23,692 - INFO - Waiting for application shutdown.
2024-10-10 07:11:23,693 - INFO - Application shutdown complete.
2024-10-10 07:11:23,693 - INFO - Finished server process [29164]
2024-10-10 07:11:25,573 - INFO - App started successfully!
2024-10-10 07:11:25,575 - INFO - Database connected successfully!
2024-10-10 07:11:25,576 - INFO - Started server process [29195]
2024-10-10 07:11:25,576 - INFO - Waiting for application startup.
2024-10-10 07:11:25,577 - INFO - Application startup complete.
2024-10-10 07:11:25,980 - INFO - Shutting down
2024-10-10 07:11:26,080 - INFO - Waiting for application shutdown.
2024-10-10 07:11:26,081 - INFO - Application shutdown complete.
2024-10-10 07:11:26,081 - INFO - Finished server process [29195]
2024-10-10 07:11:28,102 - INFO - App started successfully!
2024-10-10 07:11:28,103 - INFO - Database connected successfully!
2024-10-10 07:11:28,104 - INFO - Started server process [29213]
2024-10-10 07:11:28,105 - INFO - Waiting for application startup.
2024-10-10 07:11:28,105 - INFO - Application startup complete.
2024-10-10 07:11:28,409 - INFO - Shutting down
2024-10-10 07:11:28,510 - INFO - Waiting for application shutdown.
2024-10-10 07:11:28,510 - INFO - Application shutdown complete.
2024-10-10 07:11:28,510 - INFO - Finished server process [29213]
2024-10-10 07:11:30,061 - INFO - App started successfully!
2024-10-10 07:11:30,062 - INFO - Database connected successfully!
2024-10-10 07:11:30,063 - INFO - Started server process [29230]
2024-10-10 07:11:30,063 - INFO - Waiting for application startup.
2024-10-10 07:11:30,063 - INFO - Application startup complete.
2024-10-10 07:11:36,289 - INFO - Shutting down
2024-10-10 07:11:36,389 - INFO - Waiting for application shutdown.
2024-10-10 07:11:36,390 - INFO - Application shutdown complete.
2024-10-10 07:11:36,390 - INFO - Finished server process [29230]
2024-10-10 07:11:38,260 - INFO - App started successfully!
2024-10-10 07:11:38,262 - INFO - Database connected successfully!
2024-10-10 07:11:38,262 - INFO - Started server process [29302]
2024-10-10 07:11:38,262 - INFO - Waiting for application startup.
2024-10-10 07:11:38,263 - INFO - Application startup complete.
2024-10-10 07:11:49,910 - INFO - Shutting down
2024-10-10 07:11:50,011 - INFO - Waiting for application shutdown.
2024-10-10 07:11:50,012 - INFO - Application shutdown complete.
2024-10-10 07:11:50,013 - INFO - Finished server process [29302]
2024-10-10 07:11:51,648 - INFO - App started successfully!
2024-10-10 07:11:51,649 - INFO - Database connected successfully!
2024-10-10 07:11:51,649 - INFO - Started server process [29345]
2024-10-10 07:11:51,650 - INFO - Waiting for application startup.
2024-10-10 07:11:51,650 - INFO - Application startup complete.
2024-10-10 07:11:57,677 - INFO - Shutting down
2024-10-10 07:11:57,778 - INFO - Waiting for application shutdown.
2024-10-10 07:11:57,779 - INFO - Application shutdown complete.
2024-10-10 07:11:57,779 - INFO - Finished server process [29345]
2024-10-10 07:11:59,819 - INFO - App started successfully!
2024-10-10 07:11:59,821 - INFO - Database connected successfully!
2024-10-10 07:11:59,822 - INFO - Started server process [29404]
2024-10-10 07:11:59,822 - INFO - Waiting for application startup.
2024-10-10 07:11:59,822 - INFO - Application startup complete.
2024-10-10 07:12:00,225 - INFO - Shutting down
2024-10-10 07:12:00,326 - INFO - Waiting for application shutdown.
2024-10-10 07:12:00,326 - INFO - Application shutdown complete.
2024-10-10 07:12:00,327 - INFO - Finished server process [29404]
2024-10-10 07:12:01,968 - INFO - App started successfully!
2024-10-10 07:12:01,969 - INFO - Database connected successfully!
2024-10-10 07:12:01,970 - INFO - Started server process [29410]
2024-10-10 07:12:01,970 - INFO - Waiting for application startup.
2024-10-10 07:12:01,971 - INFO - Application startup complete.
2024-10-10 07:12:05,288 - INFO - Shutting down
2024-10-10 07:12:05,389 - INFO - Waiting for application shutdown.
2024-10-10 07:12:05,390 - INFO - Application shutdown complete.
2024-10-10 07:12:05,391 - INFO - Finished server process [29410]
2024-10-10 07:12:07,114 - INFO - App started successfully!
2024-10-10 07:12:07,115 - INFO - Database connected successfully!
2024-10-10 07:12:07,116 - INFO - Started server process [29451]
2024-10-10 07:12:07,116 - INFO - Waiting for application startup.
2024-10-10 07:12:07,116 - INFO - Application startup complete.
2024-10-10 07:12:29,407 - INFO - Shutting down
2024-10-10 07:12:29,508 - INFO - Waiting for application shutdown.
2024-10-10 07:12:29,508 - INFO - Application shutdown complete.
2024-10-10 07:12:29,509 - INFO - Finished server process [29451]
2024-10-10 07:12:31,251 - INFO - App started successfully!
2024-10-10 07:12:31,253 - INFO - Database connected successfully!
2024-10-10 07:12:31,253 - INFO - Started server process [29515]
2024-10-10 07:12:31,253 - INFO - Waiting for application startup.
2024-10-10 07:12:31,254 - INFO - Application startup complete.
2024-10-10 07:14:32,784 - INFO - Shutting down
2024-10-10 07:14:32,885 - INFO - Waiting for application shutdown.
2024-10-10 07:14:32,885 - INFO - Application shutdown complete.
2024-10-10 07:14:32,885 - INFO - Finished server process [29515]
2024-10-10 07:20:21,983 - INFO - App started successfully!
2024-10-10 07:20:21,985 - INFO - Database connected successfully!
2024-10-10 07:20:21,985 - INFO - Started server process [30784]
2024-10-10 07:20:21,985 - INFO - Waiting for application startup.
2024-10-10 07:20:21,986 - INFO - Application startup complete.
2024-10-10 07:20:23,538 - INFO - App started successfully!
2024-10-10 07:20:23,540 - INFO - Database connected successfully!
2024-10-10 07:20:23,540 - INFO - Started server process [30791]
2024-10-10 07:20:23,540 - INFO - Waiting for application startup.
2024-10-10 07:20:23,541 - INFO - Application startup complete.
2024-10-10 07:20:29,571 - INFO - Shutting down
2024-10-10 07:20:29,672 - INFO - Waiting for application shutdown.
2024-10-10 07:20:29,673 - INFO - Application shutdown complete.
2024-10-10 07:20:29,673 - INFO - Finished server process [30791]
2024-10-10 07:20:31,983 - INFO - App started successfully!
2024-10-10 07:20:31,984 - INFO - Database connected successfully!
2024-10-10 07:20:31,984 - INFO - Started server process [30839]
2024-10-10 07:20:31,985 - INFO - Waiting for application startup.
2024-10-10 07:20:31,985 - INFO - Application startup complete.
2024-10-10 07:20:32,889 - INFO - Shutting down
2024-10-10 07:20:32,990 - INFO - Waiting for application shutdown.
2024-10-10 07:20:32,990 - INFO - Application shutdown complete.
2024-10-10 07:20:32,990 - INFO - Finished server process [30839]
2024-10-10 07:21:29,356 - INFO - App started successfully!
2024-10-10 07:21:29,358 - INFO - Database connected successfully!
2024-10-10 07:21:29,359 - INFO - Started server process [31159]
2024-10-10 07:21:29,359 - INFO - Waiting for application startup.
2024-10-10 07:21:29,360 - INFO - Application startup complete.
2024-10-10 07:22:39,466 - INFO - Shutting down
2024-10-10 07:22:39,570 - INFO - Waiting for application shutdown.
2024-10-10 07:22:39,571 - INFO - Application shutdown complete.
2024-10-10 07:22:39,571 - INFO - Finished server process [31159]
2024-10-10 07:22:41,446 - INFO - App started successfully!
2024-10-10 07:22:41,447 - INFO - Database connected successfully!
2024-10-10 07:22:41,448 - INFO - Started server process [31262]
2024-10-10 07:22:41,448 - INFO - Waiting for application startup.
2024-10-10 07:22:41,448 - INFO - Application startup complete.
2024-10-10 07:22:48,979 - INFO - Shutting down
2024-10-10 07:22:49,080 - INFO - Waiting for application shutdown.
2024-10-10 07:22:49,081 - INFO - Application shutdown complete.
2024-10-10 07:22:49,081 - INFO - Finished server process [31262]
2024-10-10 07:22:50,519 - INFO - App started successfully!
2024-10-10 07:22:50,520 - INFO - Database connected successfully!
2024-10-10 07:22:50,521 - INFO - Started server process [31318]
2024-10-10 07:22:50,521 - INFO - Waiting for application startup.
2024-10-10 07:22:50,522 - INFO - Application startup complete.
2024-10-10 07:25:54,511 - INFO - Shutting down
2024-10-10 07:25:54,612 - INFO - Waiting for application shutdown.
2024-10-10 07:25:54,612 - INFO - Application shutdown complete.
2024-10-10 07:25:54,612 - INFO - Finished server process [31318]
2024-10-10 07:31:08,270 - INFO - App started successfully!
2024-10-10 07:31:08,273 - INFO - Database connected successfully!
2024-10-10 07:31:08,274 - INFO - Started server process [32179]
2024-10-10 07:31:08,274 - INFO - Waiting for application startup.
2024-10-10 07:31:08,275 - INFO - Application startup complete.
2024-10-10 07:31:50,358 - INFO - Shutting down
2024-10-10 07:31:50,459 - INFO - Waiting for application shutdown.
2024-10-10 07:31:50,459 - INFO - Application shutdown complete.
2024-10-10 07:31:50,460 - INFO - Finished server process [32179]
2024-10-10 07:31:57,867 - INFO - App started successfully!
2024-10-10 07:31:57,868 - INFO - Database connected successfully!
2024-10-10 07:31:57,868 - INFO - Started server process [32339]
2024-10-10 07:31:57,868 - INFO - Waiting for application startup.
2024-10-10 07:31:57,869 - INFO - Application startup complete.
2024-10-10 07:32:32,502 - INFO - BEGIN (implicit)
2024-10-10 07:32:32,505 - INFO - SELECT users.id AS users_id, users.first_name AS users_first_name, users.last_name AS users_last_name, users.email AS users_email, users.password AS users_password, users.created_at AS users_created_at, users.updated_at AS users_updated_at, users.is_active AS users_is_active 
FROM users 
WHERE users.email = %(email_1)s 
 LIMIT %(param_1)s
2024-10-10 07:32:32,506 - INFO - [generated in 0.00046s] {'email_1': 'samwakuedd24433329842833239@gmail.com', 'param_1': 1}
2024-10-10 07:32:32,511 - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-10-10 07:32:32,868 - INFO - INSERT INTO users (id, first_name, last_name, email, password, is_active) VALUES (%(id)s::UUID, %(first_name)s, %(last_name)s, %(email)s, %(password)s, %(is_active)s) RETURNING users.created_at, users.updated_at
2024-10-10 07:32:32,868 - INFO - [generated in 0.00065s] {'id': UUID('f7421b93-f6bc-4bd0-9543-f8b9cdbda841'), 'first_name': 'Samuel22', 'last_name': 'Wakumelo22', 'email': 'samwakuedd24433329842833239@gmail.com', 'password': '$2b$12$pCBmue07HIndiK9x8NsQC.4TPfkrxM/nuVaoSZag/XESO8kC.yBYu', 'is_active': False}
2024-10-10 07:32:32,870 - INFO - COMMIT
2024-10-10 07:32:32,879 - INFO - BEGIN (implicit)
2024-10-10 07:32:32,881 - INFO - SELECT users.id, users.first_name, users.last_name, users.email, users.password, users.created_at, users.updated_at, users.is_active 
FROM users 
WHERE users.id = %(pk_1)s::UUID
2024-10-10 07:32:32,882 - INFO - [generated in 0.00068s] {'pk_1': UUID('f7421b93-f6bc-4bd0-9543-f8b9cdbda841')}
2024-10-10 07:32:33,145 - INFO - ROLLBACK
2024-10-10 07:32:33,147 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 500, in _create_connection
    transport, _ = await asyncio.wait_for(connect_coro, timeout=self.timeout)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1036, in create_connection
    infos = await self._ensure_resolved(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1418, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
  File "/usr/lib/python3.10/asyncio/base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/connection.py", line 45, in _configure_connection
    await self.session.connect()
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 449, in connect
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 446, in connect
    response = await self._create_connection()
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 506, in _create_connection
    raise SMTPConnectError(
aiosmtplib.errors.SMTPConnectError: Error connecting to smtp.example.com on port 587: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/terminalnator/Client_portal/app/routers/user_routes.py", line 15, in signup_endpoint
    return await signup(db, user)
  File "/home/terminalnator/Client_portal/app/services/user_services.py", line 48, in signup
    await email_service.handle_email_verification(db, user.email)
  File "/home/terminalnator/Client_portal/app/services/email_services.py", line 43, in handle_email_verification
    await self.send_verification_email(email, verification_token)
  File "/home/terminalnator/Client_portal/app/services/email_services.py", line 39, in send_verification_email
    await self.fm.send_message(message)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/fastmail.py", line 109, in send_message
    async with Connection(self.config) as session:
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/connection.py", line 23, in __aenter__
    await self._configure_connection()
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/connection.py", line 53, in _configure_connection
    raise ConnectionErrors(
fastapi_mail.errors.ConnectionErrors: Exception raised Error connecting to smtp.example.com on port 587: [Errno -2] Name or service not known, check your credentials or email service configuration
2024-10-10 07:35:53,318 - INFO - Shutting down
2024-10-10 07:35:53,418 - INFO - Waiting for application shutdown.
2024-10-10 07:35:53,419 - INFO - Application shutdown complete.
2024-10-10 07:35:53,419 - INFO - Finished server process [32339]
2024-10-10 07:36:09,994 - INFO - App started successfully!
2024-10-10 07:36:09,995 - INFO - Database connected successfully!
2024-10-10 07:36:09,996 - INFO - Started server process [33583]
2024-10-10 07:36:09,996 - INFO - Waiting for application startup.
2024-10-10 07:36:09,996 - INFO - Application startup complete.
2024-10-10 07:36:13,885 - INFO - BEGIN (implicit)
2024-10-10 07:36:13,889 - INFO - SELECT users.id AS users_id, users.first_name AS users_first_name, users.last_name AS users_last_name, users.email AS users_email, users.password AS users_password, users.created_at AS users_created_at, users.updated_at AS users_updated_at, users.is_active AS users_is_active 
FROM users 
WHERE users.email = %(email_1)s 
 LIMIT %(param_1)s
2024-10-10 07:36:13,890 - INFO - [generated in 0.00054s] {'email_1': 'samwakuedd24433329842833239@gmail.com', 'param_1': 1}
2024-10-10 07:36:13,895 - INFO - ROLLBACK
2024-10-10 07:36:20,563 - INFO - BEGIN (implicit)
2024-10-10 07:36:20,564 - INFO - SELECT users.id AS users_id, users.first_name AS users_first_name, users.last_name AS users_last_name, users.email AS users_email, users.password AS users_password, users.created_at AS users_created_at, users.updated_at AS users_updated_at, users.is_active AS users_is_active 
FROM users 
WHERE users.email = %(email_1)s 
 LIMIT %(param_1)s
2024-10-10 07:36:20,564 - INFO - [cached since 6.675s ago] {'email_1': 'samwakuedd244333298424833239@gmail.com', 'param_1': 1}
2024-10-10 07:36:20,567 - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-10-10 07:36:20,914 - INFO - INSERT INTO users (id, first_name, last_name, email, password, is_active) VALUES (%(id)s::UUID, %(first_name)s, %(last_name)s, %(email)s, %(password)s, %(is_active)s) RETURNING users.created_at, users.updated_at
2024-10-10 07:36:20,914 - INFO - [generated in 0.00048s] {'id': UUID('1fd270cb-8c33-4773-b3df-8458bba19cd7'), 'first_name': 'Samuel22', 'last_name': 'Wakumelo22', 'email': 'samwakuedd244333298424833239@gmail.com', 'password': '$2b$12$9yasD4xzmUwRqtumugXRw.ZCadV.ar1hCl9Bpb1pKNLS3Z3AlBnk.', 'is_active': False}
2024-10-10 07:36:20,916 - INFO - COMMIT
2024-10-10 07:36:20,923 - INFO - BEGIN (implicit)
2024-10-10 07:36:20,926 - INFO - SELECT users.id, users.first_name, users.last_name, users.email, users.password, users.created_at, users.updated_at, users.is_active 
FROM users 
WHERE users.id = %(pk_1)s::UUID
2024-10-10 07:36:20,926 - INFO - [generated in 0.00071s] {'pk_1': UUID('1fd270cb-8c33-4773-b3df-8458bba19cd7')}
2024-10-10 07:37:20,932 - INFO - ROLLBACK
2024-10-10 07:37:20,934 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 500, in _create_connection
    transport, _ = await asyncio.wait_for(connect_coro, timeout=self.timeout)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/connection.py", line 45, in _configure_connection
    await self.session.connect()
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 449, in connect
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 446, in connect
    response = await self._create_connection()
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 502, in _create_connection
    raise SMTPConnectTimeoutError(
aiosmtplib.errors.SMTPConnectTimeoutError: Timed out connecting to smtp.gmail.com on port 587

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/terminalnator/Client_portal/app/routers/user_routes.py", line 15, in signup_endpoint
    return await signup(db, user)
  File "/home/terminalnator/Client_portal/app/services/user_services.py", line 48, in signup
    await email_service.handle_email_verification(db, user.email)
  File "/home/terminalnator/Client_portal/app/services/email_services.py", line 43, in handle_email_verification
    await self.send_verification_email(email, verification_token)
  File "/home/terminalnator/Client_portal/app/services/email_services.py", line 39, in send_verification_email
    await self.fm.send_message(message)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/fastmail.py", line 109, in send_message
    async with Connection(self.config) as session:
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/connection.py", line 23, in __aenter__
    await self._configure_connection()
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/connection.py", line 53, in _configure_connection
    raise ConnectionErrors(
fastapi_mail.errors.ConnectionErrors: Exception raised Timed out connecting to smtp.gmail.com on port 587, check your credentials or email service configuration
2024-10-10 07:54:08,777 - INFO - Shutting down
2024-10-10 07:54:08,878 - INFO - Waiting for application shutdown.
2024-10-10 07:54:08,880 - INFO - Application shutdown complete.
2024-10-10 07:54:08,881 - INFO - Finished server process [33583]
2024-10-10 07:54:10,983 - INFO - App started successfully!
2024-10-10 07:54:10,986 - INFO - Database connected successfully!
2024-10-10 07:54:10,987 - INFO - Started server process [34254]
2024-10-10 07:54:10,987 - INFO - Waiting for application startup.
2024-10-10 07:54:10,988 - INFO - Application startup complete.
2024-10-10 07:54:11,994 - INFO - Shutting down
2024-10-10 07:54:12,095 - INFO - Waiting for application shutdown.
2024-10-10 07:54:12,096 - INFO - Application shutdown complete.
2024-10-10 07:54:12,096 - INFO - Finished server process [34254]
2024-10-10 07:54:14,121 - INFO - App started successfully!
2024-10-10 07:54:14,122 - INFO - Database connected successfully!
2024-10-10 07:54:14,122 - INFO - Started server process [34285]
2024-10-10 07:54:14,123 - INFO - Waiting for application startup.
2024-10-10 07:54:14,123 - INFO - Application startup complete.
2024-10-10 07:54:21,058 - INFO - Shutting down
2024-10-10 07:54:21,160 - INFO - Waiting for application shutdown.
2024-10-10 07:54:21,161 - INFO - Application shutdown complete.
2024-10-10 07:54:21,161 - INFO - Finished server process [34285]
2024-10-10 07:54:23,072 - INFO - App started successfully!
2024-10-10 07:54:23,074 - INFO - Database connected successfully!
2024-10-10 07:54:23,074 - INFO - Started server process [34343]
2024-10-10 07:54:23,075 - INFO - Waiting for application startup.
2024-10-10 07:54:23,075 - INFO - Application startup complete.
2024-10-10 07:54:27,598 - INFO - Shutting down
2024-10-10 07:54:27,698 - INFO - Waiting for application shutdown.
2024-10-10 07:54:27,699 - INFO - Application shutdown complete.
2024-10-10 07:54:27,699 - INFO - Finished server process [34343]
2024-10-10 07:54:29,912 - INFO - App started successfully!
2024-10-10 07:54:29,913 - INFO - Database connected successfully!
2024-10-10 07:54:29,914 - INFO - Started server process [34373]
2024-10-10 07:54:29,914 - INFO - Waiting for application startup.
2024-10-10 07:54:29,914 - INFO - Application startup complete.
2024-10-10 07:54:31,747 - INFO - App started successfully!
2024-10-10 07:54:31,749 - INFO - Database connected successfully!
2024-10-10 07:54:31,750 - INFO - Started server process [34391]
2024-10-10 07:54:31,750 - INFO - Waiting for application startup.
2024-10-10 07:54:31,751 - INFO - Application startup complete.
2024-10-10 07:54:35,066 - INFO - Shutting down
2024-10-10 07:54:35,167 - INFO - Waiting for application shutdown.
2024-10-10 07:54:35,168 - INFO - Application shutdown complete.
2024-10-10 07:54:35,168 - INFO - Finished server process [34391]
2024-10-10 07:54:37,032 - INFO - App started successfully!
2024-10-10 07:54:37,033 - INFO - Database connected successfully!
2024-10-10 07:54:37,034 - INFO - Started server process [34421]
2024-10-10 07:54:37,034 - INFO - Waiting for application startup.
2024-10-10 07:54:37,035 - INFO - Application startup complete.
2024-10-10 08:02:38,638 - INFO - BEGIN (implicit)
2024-10-10 08:02:38,647 - INFO - SELECT users.id AS users_id, users.first_name AS users_first_name, users.last_name AS users_last_name, users.email AS users_email, users.password AS users_password, users.created_at AS users_created_at, users.updated_at AS users_updated_at, users.is_active AS users_is_active 
FROM users 
WHERE users.email = %(email_1)s 
 LIMIT %(param_1)s
2024-10-10 08:02:38,648 - INFO - [generated in 0.00183s] {'email_1': 'samwakuedd2443332984248335239@gmail.com', 'param_1': 1}
2024-10-10 08:02:38,657 - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-10-10 08:02:39,081 - INFO - INSERT INTO users (id, first_name, last_name, email, password, is_active) VALUES (%(id)s::UUID, %(first_name)s, %(last_name)s, %(email)s, %(password)s, %(is_active)s) RETURNING users.created_at, users.updated_at
2024-10-10 08:02:39,083 - INFO - [generated in 0.00304s] {'id': UUID('80872e53-332c-4150-9fe1-5e94e09bd001'), 'first_name': 'Samuel22', 'last_name': 'Wakumelo22', 'email': 'samwakuedd2443332984248335239@gmail.com', 'password': '$2b$12$/8Ydb2qxOPJwCvu6VlkN9OuClIMWuZj.enkTQgucxOGPWUMPYIyM2', 'is_active': False}
2024-10-10 08:02:39,086 - INFO - COMMIT
2024-10-10 08:02:39,093 - INFO - BEGIN (implicit)
2024-10-10 08:02:39,097 - INFO - SELECT users.id, users.first_name, users.last_name, users.email, users.password, users.created_at, users.updated_at, users.is_active 
FROM users 
WHERE users.id = %(pk_1)s::UUID
2024-10-10 08:02:39,097 - INFO - [generated in 0.00170s] {'pk_1': UUID('80872e53-332c-4150-9fe1-5e94e09bd001')}
2024-10-10 08:02:40,674 - INFO - ROLLBACK
2024-10-10 08:02:40,676 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/connection.py", line 48, in _configure_connection
    await self.session.login(
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 1069, in login
    raise exception or SMTPException("No suitable authentication method found.")
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 1061, in login
    response = await auth_method(username, password, timeout=timeout)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 1179, in auth_login
    raise SMTPAuthenticationError(response.code, response.message)
aiosmtplib.errors.SMTPAuthenticationError: (535, '5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 5b1f17b1804b1-431182d78dcsm6839895e9.5 - gsmtp')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/terminalnator/Client_portal/app/routers/user_routes.py", line 15, in signup_endpoint
    return await signup(db, user)
  File "/home/terminalnator/Client_portal/app/services/user_services.py", line 48, in signup
    await email_service.handle_email_verification(db, user.email)
  File "/home/terminalnator/Client_portal/app/services/email_services.py", line 46, in handle_email_verification
    await self.send_verification_email(email, verification_token)
  File "/home/terminalnator/Client_portal/app/services/email_services.py", line 42, in send_verification_email
    await self.fm.send_message(message)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/fastmail.py", line 109, in send_message
    async with Connection(self.config) as session:
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/connection.py", line 23, in __aenter__
    await self._configure_connection()
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/connection.py", line 53, in _configure_connection
    raise ConnectionErrors(
fastapi_mail.errors.ConnectionErrors: Exception raised (535, '5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 5b1f17b1804b1-431182d78dcsm6839895e9.5 - gsmtp'), check your credentials or email service configuration
2024-10-10 08:08:29,158 - INFO - Shutting down
2024-10-10 08:08:29,259 - INFO - Waiting for application shutdown.
2024-10-10 08:08:29,260 - INFO - Application shutdown complete.
2024-10-10 08:08:29,260 - INFO - Finished server process [34421]
2024-10-10 08:08:39,987 - INFO - App started successfully!
2024-10-10 08:08:39,988 - INFO - Database connected successfully!
2024-10-10 08:08:39,989 - INFO - Started server process [36083]
2024-10-10 08:08:39,989 - INFO - Waiting for application startup.
2024-10-10 08:08:39,989 - INFO - Application startup complete.
2024-10-10 08:10:18,655 - INFO - BEGIN (implicit)
2024-10-10 08:10:18,660 - INFO - SELECT users.id AS users_id, users.first_name AS users_first_name, users.last_name AS users_last_name, users.email AS users_email, users.password AS users_password, users.created_at AS users_created_at, users.updated_at AS users_updated_at, users.is_active AS users_is_active 
FROM users 
WHERE users.email = %(email_1)s 
 LIMIT %(param_1)s
2024-10-10 08:10:18,660 - INFO - [generated in 0.00037s] {'email_1': 'ikosuzy@gmail.com', 'param_1': 1}
2024-10-10 08:10:18,664 - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-10-10 08:10:19,015 - INFO - INSERT INTO users (id, first_name, last_name, email, password, is_active) VALUES (%(id)s::UUID, %(first_name)s, %(last_name)s, %(email)s, %(password)s, %(is_active)s) RETURNING users.created_at, users.updated_at
2024-10-10 08:10:19,015 - INFO - [generated in 0.00049s] {'id': UUID('11696036-e747-4e97-bb4d-c4d6aadfd96e'), 'first_name': 'Samuel22', 'last_name': 'Wakumelo22', 'email': 'ikosuzy@gmail.com', 'password': '$2b$12$HUqOAns4D8/ikmkfRCzA2.wn7lfuaQlUeY.EzE9.WyD8DNNjHk4qW', 'is_active': False}
2024-10-10 08:10:19,017 - INFO - COMMIT
2024-10-10 08:10:19,026 - INFO - BEGIN (implicit)
2024-10-10 08:10:19,028 - INFO - SELECT users.id, users.first_name, users.last_name, users.email, users.password, users.created_at, users.updated_at, users.is_active 
FROM users 
WHERE users.id = %(pk_1)s::UUID
2024-10-10 08:10:19,029 - INFO - [generated in 0.00078s] {'pk_1': UUID('11696036-e747-4e97-bb4d-c4d6aadfd96e')}
2024-10-10 08:10:24,806 - INFO - ROLLBACK
2024-10-10 08:13:58,144 - INFO - BEGIN (implicit)
2024-10-10 08:13:58,144 - INFO - SELECT users.id AS users_id, users.first_name AS users_first_name, users.last_name AS users_last_name, users.email AS users_email, users.password AS users_password, users.created_at AS users_created_at, users.updated_at AS users_updated_at, users.is_active AS users_is_active 
FROM users 
WHERE users.email = %(email_1)s 
 LIMIT %(param_1)s
2024-10-10 08:13:58,145 - INFO - [cached since 219.5s ago] {'email_1': 'largemichaels094@gmail.com', 'param_1': 1}
2024-10-10 08:13:58,490 - INFO - INSERT INTO users (id, first_name, last_name, email, password, is_active) VALUES (%(id)s::UUID, %(first_name)s, %(last_name)s, %(email)s, %(password)s, %(is_active)s) RETURNING users.created_at, users.updated_at
2024-10-10 08:13:58,491 - INFO - [cached since 219.5s ago] {'id': UUID('8d8802d8-f4a2-400b-8a1b-afa5123be2ea'), 'first_name': 'Samuel22', 'last_name': 'Wakumelo22', 'email': 'largemichaels094@gmail.com', 'password': '$2b$12$PjUyJOtybM2cJJkGGZdg.OCBh7r2A7cbycqRzeq2Mcu6SrGLNrt0K', 'is_active': False}
2024-10-10 08:13:58,493 - INFO - COMMIT
2024-10-10 08:13:58,500 - INFO - BEGIN (implicit)
2024-10-10 08:13:58,501 - INFO - SELECT users.id, users.first_name, users.last_name, users.email, users.password, users.created_at, users.updated_at, users.is_active 
FROM users 
WHERE users.id = %(pk_1)s::UUID
2024-10-10 08:13:58,501 - INFO - [cached since 219.5s ago] {'pk_1': UUID('8d8802d8-f4a2-400b-8a1b-afa5123be2ea')}
2024-10-10 08:14:58,506 - INFO - ROLLBACK
2024-10-10 08:14:58,508 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 500, in _create_connection
    transport, _ = await asyncio.wait_for(connect_coro, timeout=self.timeout)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/connection.py", line 45, in _configure_connection
    await self.session.connect()
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 449, in connect
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 446, in connect
    response = await self._create_connection()
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 502, in _create_connection
    raise SMTPConnectTimeoutError(
aiosmtplib.errors.SMTPConnectTimeoutError: Timed out connecting to smtp.gmail.com on port 587

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/terminalnator/Client_portal/app/routers/user_routes.py", line 15, in signup_endpoint
    return await signup(db, user)
  File "/home/terminalnator/Client_portal/app/services/user_services.py", line 48, in signup
    await email_service.handle_email_verification(db, user.email)
  File "/home/terminalnator/Client_portal/app/services/email_services.py", line 46, in handle_email_verification
    await self.send_verification_email(email, verification_token)
  File "/home/terminalnator/Client_portal/app/services/email_services.py", line 42, in send_verification_email
    await self.fm.send_message(message)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/fastmail.py", line 109, in send_message
    async with Connection(self.config) as session:
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/connection.py", line 23, in __aenter__
    await self._configure_connection()
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/connection.py", line 53, in _configure_connection
    raise ConnectionErrors(
fastapi_mail.errors.ConnectionErrors: Exception raised Timed out connecting to smtp.gmail.com on port 587, check your credentials or email service configuration
2024-10-10 08:15:26,651 - INFO - BEGIN (implicit)
2024-10-10 08:15:26,652 - INFO - SELECT users.id AS users_id, users.first_name AS users_first_name, users.last_name AS users_last_name, users.email AS users_email, users.password AS users_password, users.created_at AS users_created_at, users.updated_at AS users_updated_at, users.is_active AS users_is_active 
FROM users 
WHERE users.email = %(email_1)s 
 LIMIT %(param_1)s
2024-10-10 08:15:26,652 - INFO - [cached since 308s ago] {'email_1': 'largemichaels094@gmail.com', 'param_1': 1}
2024-10-10 08:15:26,654 - INFO - ROLLBACK
2024-10-10 08:19:14,742 - INFO - BEGIN (implicit)
2024-10-10 08:19:14,743 - INFO - SELECT users.id AS users_id, users.first_name AS users_first_name, users.last_name AS users_last_name, users.email AS users_email, users.password AS users_password, users.created_at AS users_created_at, users.updated_at AS users_updated_at, users.is_active AS users_is_active 
FROM users 
WHERE users.email = %(email_1)s 
 LIMIT %(param_1)s
2024-10-10 08:19:14,744 - INFO - [cached since 536.1s ago] {'email_1': 'largemichaels094@gmail.com', 'param_1': 1}
2024-10-10 08:19:14,746 - INFO - ROLLBACK
2024-10-10 08:25:35,824 - INFO - BEGIN (implicit)
2024-10-10 08:25:35,824 - INFO - SELECT users.id AS users_id, users.first_name AS users_first_name, users.last_name AS users_last_name, users.email AS users_email, users.password AS users_password, users.created_at AS users_created_at, users.updated_at AS users_updated_at, users.is_active AS users_is_active 
FROM users 
WHERE users.email = %(email_1)s 
 LIMIT %(param_1)s
2024-10-10 08:25:35,825 - INFO - [cached since 917.2s ago] {'email_1': 'largemichaels094@gmail.com', 'param_1': 1}
2024-10-10 08:25:36,164 - INFO - INSERT INTO users (id, first_name, last_name, email, password, is_active) VALUES (%(id)s::UUID, %(first_name)s, %(last_name)s, %(email)s, %(password)s, %(is_active)s) RETURNING users.created_at, users.updated_at
2024-10-10 08:25:36,165 - INFO - [cached since 917.2s ago] {'id': UUID('203de39f-36f2-46d3-b95d-4ebf040e4a08'), 'first_name': 'Samuel22', 'last_name': 'Wakumelo22', 'email': 'largemichaels094@gmail.com', 'password': '$2b$12$UVbVK3Kv7joZH/V1PI2jjOOHCqwYQIrvpiedi5uS6MiMdwQvtcm.O', 'is_active': False}
2024-10-10 08:25:36,170 - INFO - COMMIT
2024-10-10 08:25:36,179 - INFO - BEGIN (implicit)
2024-10-10 08:25:36,180 - INFO - SELECT users.id, users.first_name, users.last_name, users.email, users.password, users.created_at, users.updated_at, users.is_active 
FROM users 
WHERE users.id = %(pk_1)s::UUID
2024-10-10 08:25:36,181 - INFO - [cached since 917.2s ago] {'pk_1': UUID('203de39f-36f2-46d3-b95d-4ebf040e4a08')}
2024-10-10 08:25:43,050 - INFO - ROLLBACK
2024-10-10 08:36:27,201 - INFO - Shutting down
2024-10-10 08:36:27,303 - INFO - Waiting for application shutdown.
2024-10-10 08:36:27,304 - INFO - Application shutdown complete.
2024-10-10 08:36:27,304 - INFO - Finished server process [36083]
2024-10-10 08:36:29,291 - INFO - App started successfully!
2024-10-10 08:36:29,292 - INFO - Database connected successfully!
2024-10-10 08:36:29,293 - INFO - Started server process [39970]
2024-10-10 08:36:29,293 - INFO - Waiting for application startup.
2024-10-10 08:36:29,294 - INFO - Application startup complete.
2024-10-10 08:40:42,389 - INFO - BEGIN (implicit)
2024-10-10 08:40:42,398 - INFO - SELECT users.id AS users_id, users.first_name AS users_first_name, users.last_name AS users_last_name, users.email AS users_email, users.password AS users_password, users.created_at AS users_created_at, users.updated_at AS users_updated_at, users.is_active AS users_is_active 
FROM users 
WHERE users.email = %(email_1)s 
 LIMIT %(param_1)s
2024-10-10 08:40:42,398 - INFO - [generated in 0.00118s] {'email_1': 'largemichaels094@gmail.com', 'param_1': 1}
2024-10-10 08:40:42,406 - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2024-10-10 08:40:42,775 - INFO - INSERT INTO users (id, first_name, last_name, email, password, is_active) VALUES (%(id)s::UUID, %(first_name)s, %(last_name)s, %(email)s, %(password)s, %(is_active)s) RETURNING users.created_at, users.updated_at
2024-10-10 08:40:42,775 - INFO - [generated in 0.00048s] {'id': UUID('010def42-df07-4baf-966f-4aee2bd9943d'), 'first_name': 'Samuel22', 'last_name': 'Wakumelo22', 'email': 'largemichaels094@gmail.com', 'password': '$2b$12$7NFH6k5cha8weAx6WPhyK.o3fd3C7SR3V2ZTBN4.nye0ek7oQjylq', 'is_active': False}
2024-10-10 08:40:42,778 - INFO - COMMIT
2024-10-10 08:40:42,784 - INFO - BEGIN (implicit)
2024-10-10 08:40:42,786 - INFO - SELECT users.id, users.first_name, users.last_name, users.email, users.password, users.created_at, users.updated_at, users.is_active 
FROM users 
WHERE users.id = %(pk_1)s::UUID
2024-10-10 08:40:42,786 - INFO - [generated in 0.00056s] {'pk_1': UUID('010def42-df07-4baf-966f-4aee2bd9943d')}
2024-10-10 08:41:42,794 - INFO - ROLLBACK
2024-10-10 08:41:42,797 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 500, in _create_connection
    transport, _ = await asyncio.wait_for(connect_coro, timeout=self.timeout)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/connection.py", line 45, in _configure_connection
    await self.session.connect()
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 449, in connect
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 446, in connect
    response = await self._create_connection()
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/aiosmtplib/smtp.py", line 502, in _create_connection
    raise SMTPConnectTimeoutError(
aiosmtplib.errors.SMTPConnectTimeoutError: Timed out connecting to smtp.gmail.com on port 587

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/terminalnator/Client_portal/app/routers/user_routes.py", line 15, in signup_endpoint
    return await signup(db, user)
  File "/home/terminalnator/Client_portal/app/services/user_services.py", line 48, in signup
    await email_service.handle_email_verification(db, user.email)
  File "/home/terminalnator/Client_portal/app/services/email_services.py", line 46, in handle_email_verification
    await self.send_verification_email(email, verification_token)
  File "/home/terminalnator/Client_portal/app/services/email_services.py", line 42, in send_verification_email
    await self.fm.send_message(message)
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/fastmail.py", line 109, in send_message
    async with Connection(self.config) as session:
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/connection.py", line 23, in __aenter__
    await self._configure_connection()
  File "/home/terminalnator/Client_portal/venv/lib/python3.10/site-packages/fastapi_mail/connection.py", line 53, in _configure_connection
    raise ConnectionErrors(
fastapi_mail.errors.ConnectionErrors: Exception raised Timed out connecting to smtp.gmail.com on port 587, check your credentials or email service configuration
